'use client'
import { ResponsiveContainer, LineChart, Line, BarChart, Bar, ComposedChart, CartesianGrid, XAxis, YAxis, Tooltip, Legend, ReferenceLine, PieChart, Pie, Cell, ScatterChart, Scatter, ZAxis } from 'recharts'

const C={blue:'#2d8cff',cyan:'#28c8ee',green:'#32d19a',orange:'#ff8d43',yellow:'#f2bb4f',red:'#f06464',purple:'#9d7cff',muted:'#6f8da1',grid:'#17364b'}
const palette=[C.blue,C.green,C.orange,C.purple,C.yellow,C.cyan,C.red,'#82a8c3']
const tick={fill:'#8ea5b6',fontSize:11}
export const ChartTip=({active,payload,label})=> active&&payload?.length?<div className="chart-tip"><b>{label}</b>{payload.filter(p=>p.value!==undefined&&p.value!==null).map((p,i)=><span key={i}>{p.name}: {typeof p.value==='number'?p.value.toLocaleString('pt-BR',{maximumFractionDigits:2}):p.value}</span>)}</div>:null
export function TrendChart({data,percent=true}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:10,right:14,left:0,bottom:2}}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick} domain={percent?[0,1]:['auto','auto']} tickFormatter={v=>percent?`${Math.round(v*100)}%`:v}/><Tooltip content={<ChartTip/>}/><Legend/><Line type="monotone" dataKey="oee" name="OEE" stroke={C.blue} strokeWidth={2.3} dot={false}/><Line type="monotone" dataKey="adherence" name="Aderência" stroke={C.green} strokeWidth={2.3} dot={false}/><Line type="monotone" dataKey="otif" name="OTIF" stroke={C.orange} strokeWidth={2.3} dot={false}/><Line type="monotone" dataKey="margin" name="Margem EBITDA" stroke={C.yellow} strokeWidth={2.3} dot={false}/></LineChart></ResponsiveContainer></div> }
export function HorizontalBars({data,dataKey='impact',nameKey='name',color=C.red}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{top:2,right:20,left:20,bottom:2}}><CartesianGrid stroke={C.grid} horizontal={false}/><XAxis type="number" tick={tick}/><YAxis type="category" dataKey={nameKey} width={145} tick={tick}/><Tooltip content={<ChartTip/>}/><Bar dataKey={dataKey} fill={color} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div> }
export function HealthDonut({score,status=[]}){ const counts={good:status.filter(x=>x.state==='good').length,warn:status.filter(x=>x.state==='warn').length,bad:status.filter(x=>x.state==='bad').length}; const data=[{name:'Saudável',value:counts.good,color:C.green},{name:'Atenção',value:counts.warn,color:C.yellow},{name:'Crítico',value:counts.bad,color:C.red}].filter(x=>x.value>0); return <div className="health-wrap"><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.length?data:[{value:1,color:C.muted}]} dataKey="value" innerRadius="67%" outerRadius="91%" stroke="none">{(data.length?data:[{color:C.muted}]).map((e,i)=><Cell key={i} fill={e.color}/>)}</Pie></PieChart></ResponsiveContainer><div className="donut-center"><strong>{Math.round(score||0)}</strong><span>Saúde</span></div></div><div className="health-counts"><div><strong className="good">{counts.good}</strong><span>acima/meta</span></div><div><strong className="warn">{counts.warn}</strong><span>atenção</span></div><div><strong className="bad">{counts.bad}</strong><span>críticos</span></div></div></div> }
export function OeePlantChart({data=[]}){
 const rows=(Array.isArray(data)?data:[]).filter(Boolean); if(!rows.length)return <div className="chart-empty">Sem dados de OEE por planta.</div>
 const W=900,H=300,padL=55,padR=16,padT=18,padB=55,plotW=W-padL-padR,plotH=H-padT-padB; const groupW=plotW/rows.length; const bw=Math.max(8,Math.min(22,groupW/6));
 const y=v=>padT+plotH*(1-Math.max(0,Math.min(1,Number(v)||0))); const series=[['oee',C.blue],['availability',C.cyan],['performance',C.orange],['quality',C.purple]];
 return <div className="chart safe-svg-chart"><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="OEE por planta">{[0,.25,.5,.75,1].map((v,i)=><g key={i}><line x1={padL} x2={W-padR} y1={y(v)} y2={y(v)} stroke={C.grid}/><text x={padL-8} y={y(v)+4} textAnchor="end" fill="#8ea5b6" fontSize="10">{Math.round(v*100)}%</text></g>)}<line x1={padL} x2={W-padR} y1={y(.85)} y2={y(.85)} stroke={C.cyan} strokeDasharray="6 5"/>{rows.map((r,idx)=>{const cx=padL+groupW*(idx+.5);return <g key={r.plant||idx}>{series.map(([k,color],j)=>{const v=Math.max(0,Math.min(1,Number(r?.[k])||0));const x=cx+(j-1.5)*(bw+3);return <rect key={k} x={x-bw/2} y={y(v)} width={bw} height={Math.max(1,padT+plotH-y(v))} rx="3" fill={color}/>})}<text x={cx} y={H-28} textAnchor="middle" fill="#a9bdc9" fontSize="10">{String(r.plant||'').replace('Planta ','')}</text><text x={cx} y={y(r.oee)-7} textAnchor="middle" fill="#fff" fontSize="10" fontWeight="700">{Math.round((Number(r.oee)||0)*100)}%</text></g>})}<g transform={`translate(${padL},${H-8})`}>{series.map(([k,color],i)=><g key={k} transform={`translate(${i*150},0)`}><rect width="9" height="9" rx="2" fill={color}/><text x="14" y="8" fill="#8ea5b6" fontSize="9">{{oee:'OEE',availability:'Disponibilidade',performance:'Performance',quality:'Qualidade'}[k]}</text></g>)}</g></svg></div>
}

export function SimpleBars({data=[],nameKey='plant',valueKey='production',color=C.blue}){
 const rows=(Array.isArray(data)?data:[]).filter(Boolean); const max=Math.max(...rows.map(x=>Math.abs(Number(x?.[valueKey])||0)),1)
 return <div className="safe-bars">{rows.map((r,i)=>{const v=Number(r?.[valueKey])||0;return <div className="safe-bar-row" key={r?.[nameKey]||i}><span>{String(r?.[nameKey]??'—').replace('Planta ','')}</span><div className="safe-bar-track"><i style={{width:`${Math.max(2,Math.abs(v)/max*100)}%`,background:color}}/></div><b>{Math.abs(v)>=1e6?`${(v/1e6).toLocaleString('pt-BR',{maximumFractionDigits:2})} mi`:Math.abs(v)>=1e3?`${(v/1e3).toLocaleString('pt-BR',{maximumFractionDigits:0})} mil`:v.toLocaleString('pt-BR',{maximumFractionDigits:2})}</b></div>})}</div>
}

export function OeeTrend({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick} domain={[0,1]} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip content={<ChartTip/>}/><Legend/><ReferenceLine y={.85} stroke={C.cyan} strokeDasharray="5 5"/><Bar dataKey="oee" name="OEE" fill={C.blue}/><Line dataKey="availability" name="Disponibilidade" stroke={C.green}/><Line dataKey="performance" name="Performance" stroke={C.orange}/><Line dataKey="quality" name="Qualidade" stroke={C.purple}/></ComposedChart></ResponsiveContainer></div> }
export function ForecastChart({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick}/><Tooltip content={<ChartTip/>}/><Legend/><Bar dataKey="forecast" name="Forecast" fill={C.blue}/><Bar dataKey="plan" name="MRP / Plano" fill={C.green}/><Line dataKey="produced" name="Produzido" stroke={C.orange} strokeWidth={2.5}/></ComposedChart></ResponsiveContainer></div> }
export function CapacityChart({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis yAxisId="left" tick={tick}/><YAxis yAxisId="right" orientation="right" tick={tick} domain={[0,1]} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip content={<ChartTip/>}/><Legend/><Bar yAxisId="left" dataKey="capacity" name="Capacidade Nominal" fill="#7289a1"/><Bar yAxisId="left" dataKey="production" name="Produção Real" fill={C.blue}/><Line yAxisId="right" dataKey="utilization" name="Utilização" stroke={C.orange} strokeWidth={2.3}/></ComposedChart></ResponsiveContainer></div> }
export function ServiceChart({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick} domain={[0,1]} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip content={<ChartTip/>}/><Legend/><ReferenceLine y={.95} stroke={C.cyan} strokeDasharray="5 5"/><Bar dataKey="otif" name="OTIF" fill={C.blue}/><Line dataKey="on_time" name="On Time" stroke={C.cyan}/><Line dataKey="in_full" name="In Full" stroke={C.green}/></ComposedChart></ResponsiveContainer></div> }
export function CostDonut({data=[]}){
 const safe=(Array.isArray(data)?data:[]).filter(x=>Number(x?.value)>0); const total=safe.reduce((a,x)=>a+Number(x.value||0),0); if(!total)return <div className="chart-empty">Sem composição positiva para exibir.</div>
 let acc=0; const stops=safe.map((x,i)=>{const a=acc/total*100;acc+=Number(x.value||0);const b=acc/total*100;return `${palette[i%palette.length]} ${a}% ${b}%`}).join(',');
 return <div className="safe-donut-wrap"><div className="safe-donut" style={{background:`conic-gradient(${stops})`}}><div><strong>{(total/1e6).toLocaleString('pt-BR',{maximumFractionDigits:1})} mi</strong><span>Total</span></div></div><div className="safe-donut-legend">{safe.map((x,i)=><div key={i}><i style={{background:palette[i%palette.length]}}/><span>{x.name}</span><b>{(Number(x.value)/total*100).toLocaleString('pt-BR',{maximumFractionDigits:0})}%</b></div>)}</div></div>
}

export function MatrixChart({data=[],impactSplit=null,effortSplit=2.5}){
 const rows=(Array.isArray(data)?data:[]).filter(x=>Number.isFinite(Number(x?.impact))&&Number.isFinite(Number(x?.effort))); if(!rows.length)return <div className="chart-empty">Sem ações monetizadas para a matriz.</div>
 const W=620,H=390,padL=62,padR=18,padT=24,padB=48,plotW=W-padL-padR,plotH=H-padT-padB; const maxImpact=Math.max(...rows.map(x=>Number(x.impact)||0),1)*1.12; const split=impactSplit==null?[...rows].sort((a,b)=>a.impact-b.impact)[Math.floor(rows.length/2)]?.impact||maxImpact/2:Number(impactSplit); const x=e=>padL+Math.max(0,Math.min(5,Number(e)||0))/5*plotW; const y=v=>padT+plotH*(1-Math.max(0,Math.min(maxImpact,Number(v)||0))/maxImpact); const sy=y(split),sx=x(effortSplit); const color=q=>q==='Quick Wins'?C.green:q==='Grandes Projetos'?C.red:q==='Melhorias Incrementais'?C.blue:C.yellow;
 const qOf=r=>r.quadrant||((r.effort<=2&&r.impact>=split)?'Quick Wins':(r.effort>2&&r.impact>=split)?'Grandes Projetos':r.effort<=2?'Melhorias Incrementais':'Projetos Estruturantes');
 return <div className="chart matrix-chart-safe"><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Matriz Impacto por Esforço"><rect x={padL} y={padT} width={sx-padL} height={sy-padT} fill="rgba(50,209,154,.12)"/><rect x={sx} y={padT} width={W-padR-sx} height={sy-padT} fill="rgba(240,100,100,.11)"/><rect x={padL} y={sy} width={sx-padL} height={H-padB-sy} fill="rgba(45,140,255,.10)"/><rect x={sx} y={sy} width={W-padR-sx} height={H-padB-sy} fill="rgba(242,187,79,.10)"/><line x1={sx} x2={sx} y1={padT} y2={H-padB} stroke="#557286" strokeDasharray="5 5"/><line x1={padL} x2={W-padR} y1={sy} y2={sy} stroke="#557286" strokeDasharray="5 5"/><text x={padL+10} y={padT+18} fill={C.green} fontSize="12" fontWeight="700">Quick Wins</text><text x={W-padR-10} y={padT+18} textAnchor="end" fill={C.red} fontSize="12" fontWeight="700">Grandes Projetos</text><text x={padL+10} y={H-padB-12} fill={C.blue} fontSize="12" fontWeight="700">Melhorias Incrementais</text><text x={W-padR-10} y={H-padB-12} textAnchor="end" fill={C.yellow} fontSize="12" fontWeight="700">Projetos Estruturantes</text>{[0,.25,.5,.75,1].map((f,i)=><g key={i}><line x1={padL} x2={W-padR} y1={padT+plotH*(1-f)} y2={padT+plotH*(1-f)} stroke={C.grid}/><text x={padL-8} y={padT+plotH*(1-f)+4} textAnchor="end" fill="#8ea5b6" fontSize="9">{Math.round(maxImpact*f/1000)}k</text></g>)}{[0,1,2,3,4,5].map(v=><text key={v} x={x(v)} y={H-24} textAnchor="middle" fill="#8ea5b6" fontSize="9">{v}</text>)}{rows.map((r,i)=><g key={r.name||i}><circle cx={x(r.effort)} cy={y(r.impact)} r="7" fill={color(qOf(r))} stroke="#dce9f0" strokeWidth="1"><title>{`${r.name} · ${qOf(r)} · esforço ${r.effort} · impacto ${Number(r.impact).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})}`}</title></circle></g>)}<text x={(padL+W-padR)/2} y={H-5} textAnchor="middle" fill="#a9bdc9" fontSize="10">Esforço de implementação</text><text transform={`translate(12 ${(padT+H-padB)/2}) rotate(-90)`} textAnchor="middle" fill="#a9bdc9" fontSize="10">Impacto financeiro</text></svg></div>
}

export function MultiPlantTrend({data=[]}){
 const rows=(Array.isArray(data)?data:[]).filter(Boolean); const plants=[...new Set(rows.map(x=>x.plant).filter(Boolean))]; const periods=[...new Set(rows.map(x=>x.period).filter(Boolean))]; if(!plants.length||!periods.length)return <div className="chart-empty">Sem evolução multiplantas disponível.</div>
 const W=900,H=300,padL=48,padR=18,padT=22,padB=48,plotW=W-padL-padR,plotH=H-padT-padB; const x=i=>padL+(periods.length<=1?plotW/2:i/(periods.length-1)*plotW); const y=v=>padT+plotH*(1-Math.max(0,Math.min(1,Number(v)||0))); const lookup=new Map(rows.map(r=>[`${r.plant}__${r.period}`,r.oee]));
 return <div className="chart safe-svg-chart"><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Evolução do OEE por planta">{[0,.25,.5,.75,1].map((v,i)=><g key={i}><line x1={padL} x2={W-padR} y1={y(v)} y2={y(v)} stroke={C.grid}/><text x={padL-7} y={y(v)+4} textAnchor="end" fill="#8ea5b6" fontSize="9">{Math.round(v*100)}%</text></g>)}<line x1={padL} x2={W-padR} y1={y(.85)} y2={y(.85)} stroke={C.cyan} strokeDasharray="5 5"/>{plants.map((p,pi)=>{const pts=periods.map((period,i)=>({x:x(i),y:y(lookup.get(`${p}__${period}`)),v:lookup.get(`${p}__${period}`)})).filter(z=>z.v!==undefined&&z.v!==null);return <g key={p}><polyline points={pts.map(z=>`${z.x},${z.y}`).join(' ')} fill="none" stroke={palette[pi%palette.length]} strokeWidth="2.5"/>{pts.map((z,i)=><circle key={i} cx={z.x} cy={z.y} r="2.8" fill={palette[pi%palette.length]}/>)}</g>})}{periods.map((period,i)=><text key={period} x={x(i)} y={H-28} textAnchor="middle" fill="#8ea5b6" fontSize="9">{period}</text>)}<g transform={`translate(${padL},${H-8})`}>{plants.map((p,i)=><g key={p} transform={`translate(${i*170},0)`}><line x2="14" stroke={palette[i%palette.length]} strokeWidth="3"/><text x="19" y="3" fill="#8ea5b6" fontSize="9">{String(p).replace('Planta ','')}</text></g>)}</g></svg></div>
}

export function FamilyWeekChart({data=[]}){ const fams=[...new Set(data.map(x=>x.family))]; const weeks=[...new Set(data.map(x=>x.week))]; const rows=weeks.map(week=>{const r={week};data.filter(x=>x.week===week).forEach(x=>{r[x.family]=x.wape});return r}); return <div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={rows}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="week" tick={tick}/><YAxis tick={tick} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip content={<ChartTip/>}/><Legend/>{fams.map((f,i)=><Line key={f} dataKey={f} name={f} stroke={palette[i%palette.length]} dot={false} strokeWidth={2}/>)}</LineChart></ResponsiveContainer></div> }
export function MaterialTrend({data=[]}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick}/><Tooltip content={<ChartTip/>}/><Legend/><Bar dataKey="actual" name="Consumo Real kg/un" fill={C.blue}/><Line dataKey="standard" name="Consumo Padrão kg/un" stroke={C.cyan} strokeWidth={2.4}/></ComposedChart></ResponsiveContainer></div> }
export function SupplierChart({data=[]}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data.slice(0,8)}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="supplier" tick={tick}/><YAxis yAxisId="d" tick={tick}/><YAxis yAxisId="p" orientation="right" domain={[0,1]} tick={tick} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip content={<ChartTip/>}/><Legend/><Bar yAxisId="d" dataKey="lead_time" name="Lead Time (dias)" fill={C.blue}/><Line yAxisId="p" dataKey="adherence" name="Aderência" stroke={C.green} strokeWidth={2.3}/></ComposedChart></ResponsiveContainer></div> }
export function FinanceTrend({data=[]}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick} tickFormatter={v=>`${(v/1e6).toLocaleString('pt-BR',{maximumFractionDigits:1})} mi`}/><Tooltip content={<ChartTip/>}/><Legend/><Line dataKey="revenue" name="Receita Líquida" stroke={C.blue} strokeWidth={2.3} dot={false}/><Line dataKey="industrial_margin" name="Margem Industrial" stroke={C.green} strokeWidth={2.3} dot={false}/><Line dataKey="ebitda" name="EBITDA Gerencial" stroke={C.orange} strokeWidth={2.3} dot={false}/></LineChart></ResponsiveContainer></div> }
export function BridgeChart({current=0,projected=0,items=[]}){
 const it=(Array.isArray(items)?items:[]).map(x=>({...x,impact:Number(x?.impact)||0})); const cur=Number(current)||0,proj=Number(projected)||0; let run=cur; const rows=[{name:'EBITDA Atual',from:0,to:cur,type:'total',display:cur}]; for(const x of it){const next=run+x.impact;rows.push({name:x.label||'Driver',from:Math.min(run,next),to:Math.max(run,next),type:x.impact>=0?'pos':'neg',display:x.impact});run=next} rows.push({name:'EBITDA Final',from:0,to:proj,type:'total',display:proj}); const vals=rows.flatMap(r=>[r.from,r.to,0]); const min=Math.min(...vals),max=Math.max(...vals); const span=Math.max(max-min,1); const W=1000,H=360,padL=65,padR=18,padT=25,padB=86,plotW=W-padL-padR,plotH=H-padT-padB; const bw=Math.max(12,Math.min(45,plotW/rows.length*.58)); const x=i=>padL+(i+.5)/rows.length*plotW; const y=v=>padT+(max-v)/span*plotH; const col=t=>t==='pos'?C.green:t==='neg'?C.red:C.blue;
 return <div className="chart chart-lg safe-svg-chart"><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Bridge de EBITDA">{rows.map((r,i)=>{const top=Math.min(y(r.to),y(r.from)),h=Math.max(2,Math.abs(y(r.to)-y(r.from)));return <g key={`${r.name}-${i}`}><rect x={x(i)-bw/2} y={top} width={bw} height={h} rx="4" fill={col(r.type)}/><text x={x(i)} y={Math.max(12,top-7)} textAnchor="middle" fill="#dce9f0" fontSize="9">{(r.display/1e6).toLocaleString('pt-BR',{maximumFractionDigits:1})}</text><text transform={`translate(${x(i)+4} ${H-70}) rotate(-35)`} textAnchor="end" fill="#8ea5b6" fontSize="8">{r.name}</text>{i<rows.length-1&&<line x1={x(i)+bw/2} x2={x(i+1)-bw/2} y1={y(r.to)} y2={y(r.to)} stroke="#4e6e82" strokeDasharray="3 3"/>}</g>})}<line x1={padL} x2={W-padR} y1={y(0)} y2={y(0)} stroke="#557286"/></svg></div>
}
