'use client'
import { ResponsiveContainer, LineChart, Line, BarChart, Bar, ComposedChart, CartesianGrid, XAxis, YAxis, Tooltip, Legend, ReferenceLine, PieChart, Pie, Cell, ScatterChart, Scatter, ZAxis } from 'recharts'

const C={blue:'#2d8cff',cyan:'#28c8ee',green:'#32d19a',orange:'#ff8d43',yellow:'#f2bb4f',red:'#f06464',purple:'#9d7cff',muted:'#6f8da1',grid:'#17364b'}
const tick={fill:'#8ea5b6',fontSize:11}
export const ChartTip=({active,payload,label})=> active&&payload?.length?<div className="chart-tip"><b>{label}</b>{payload.map((p,i)=><span key={i}>{p.name}: {typeof p.value==='number'?p.value.toLocaleString('pt-BR',{maximumFractionDigits:2}):p.value}</span>)}</div>:null
export function TrendChart({data,percent=true}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:10,right:14,left:0,bottom:2}}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick} domain={percent?[0,1]:['auto','auto']} tickFormatter={v=>percent?`${Math.round(v*100)}%`:v}/><Tooltip content={<ChartTip/>}/><Legend/><Line type="monotone" dataKey="oee" name="OEE" stroke={C.blue} strokeWidth={2.3} dot={false}/><Line type="monotone" dataKey="adherence" name="Aderência" stroke={C.green} strokeWidth={2.3} dot={false}/><Line type="monotone" dataKey="otif" name="OTIF" stroke={C.orange} strokeWidth={2.3} dot={false}/><Line type="monotone" dataKey="margin" name="Margem EBITDA" stroke={C.yellow} strokeWidth={2.3} dot={false}/></LineChart></ResponsiveContainer></div> }
export function HorizontalBars({data,dataKey='impact',nameKey='name',color=C.red,valueFormatter}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{top:2,right:20,left:20,bottom:2}}><CartesianGrid stroke={C.grid} horizontal={false}/><XAxis type="number" tick={tick}/><YAxis type="category" dataKey={nameKey} width={130} tick={tick}/><Tooltip content={<ChartTip/>}/><Bar dataKey={dataKey} fill={color} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div> }
export function HealthDonut({score,status=[]}){ const weights={OEE:35,PCP:20,Capacidade:15,Materiais:15,OTIF:15};const counts={good:status.filter(x=>x.state==='good').length,warn:status.filter(x=>x.state==='warn').length,bad:status.filter(x=>x.state==='bad').length}; const data=[{name:'Saudável',value:status.filter(x=>x.state==='good').reduce((a,x)=>a+(weights[x.key]||0),0),color:C.green},{name:'Atenção',value:status.filter(x=>x.state==='warn').reduce((a,x)=>a+(weights[x.key]||0),0),color:C.yellow},{name:'Crítico',value:status.filter(x=>x.state==='bad').reduce((a,x)=>a+(weights[x.key]||0),0),color:C.red},{name:'Sem dados',value:status.filter(x=>x.state==='na').reduce((a,x)=>a+(weights[x.key]||0),0),color:C.muted}].filter(x=>x.value>0); return <div className="health-wrap"><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.length?data:[{value:1,color:C.muted}]} dataKey="value" innerRadius="67%" outerRadius="91%" stroke="none">{(data.length?data:[{color:C.muted}]).map((e,i)=><Cell key={i} fill={e.color}/>)}</Pie><Tooltip content={<ChartTip/>}/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{score==null?'N/D':Math.round(score)}</strong><span>Saúde ponderada</span></div></div><div className="health-counts"><div><strong className="good">{counts.good}</strong><span>acima/meta</span></div><div><strong className="warn">{counts.warn}</strong><span>atenção</span></div><div><strong className="bad">{counts.bad}</strong><span>críticos</span></div></div></div> }
export function OeePlantChart({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{top:10,right:10,left:0,bottom:2}}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="plant" tick={tick}/><YAxis tick={tick} domain={[0,1]} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip content={<ChartTip/>}/><Legend/><ReferenceLine y={.85} stroke={C.cyan} strokeDasharray="6 5" label={{value:'Meta OEE 85%',fill:'#9ccfe0',fontSize:10}}/><Bar dataKey="oee" name="OEE" fill={C.blue} radius={[4,4,0,0]}/><Line type="monotone" dataKey="availability" name="Disponibilidade" stroke={C.cyan} strokeWidth={2}/><Line type="monotone" dataKey="performance" name="Performance" stroke={C.orange} strokeWidth={2}/><Line type="monotone" dataKey="quality" name="Qualidade" stroke={C.purple} strokeWidth={2}/></ComposedChart></ResponsiveContainer></div> }
export function SimpleBars({data,nameKey='plant',valueKey='production',color=C.blue}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{top:8,right:14,left:4,bottom:4}}><CartesianGrid stroke={C.grid} horizontal={false}/><XAxis type="number" tick={tick}/><YAxis type="category" dataKey={nameKey} width={100} tick={tick}/><Tooltip content={<ChartTip/>}/><Bar dataKey={valueKey} fill={color} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div> }
export function OeeTrend({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick} domain={[0,1]} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip content={<ChartTip/>}/><Legend/><ReferenceLine y={.85} stroke={C.cyan} strokeDasharray="5 5"/><Bar dataKey="oee" name="OEE" fill={C.blue}/><Line dataKey="availability" name="Disponibilidade" stroke={C.green}/><Line dataKey="performance" name="Performance" stroke={C.orange}/><Line dataKey="quality" name="Qualidade" stroke={C.purple}/></ComposedChart></ResponsiveContainer></div> }
export function ForecastChart({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick}/><Tooltip content={<ChartTip/>}/><Legend/><Bar dataKey="forecast" name="Forecast" fill={C.blue}/><Bar dataKey="plan" name="MRP / Plano" fill={C.green}/><Line dataKey="produced" name="Produzido" stroke={C.orange} strokeWidth={2.5}/></ComposedChart></ResponsiveContainer></div> }
export function CapacityChart({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis yAxisId="left" tick={tick}/><YAxis yAxisId="right" orientation="right" tick={tick} domain={[0,1]} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip content={<ChartTip/>}/><Legend/><Bar yAxisId="left" dataKey="capacity" name="Capacidade Nominal" fill="#7289a1"/><Bar yAxisId="left" dataKey="production" name="Produção Real" fill={C.blue}/><Line yAxisId="right" dataKey="utilization" name="Utilização" stroke={C.orange} strokeWidth={2.3}/></ComposedChart></ResponsiveContainer></div> }
export function ServiceChart({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick} domain={[0,1]} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip content={<ChartTip/>}/><Legend/><ReferenceLine y={.95} stroke={C.cyan} strokeDasharray="5 5"/><Bar dataKey="otif" name="OTIF" fill={C.blue}/><Line dataKey="on_time" name="On Time" stroke={C.cyan}/><Line dataKey="in_full" name="In Full" stroke={C.green}/></ComposedChart></ResponsiveContainer></div> }
export function CostDonut({data}){ const colors=[C.blue,C.orange,C.green,C.purple,C.yellow]; return <div className="chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius="55%" outerRadius="80%" stroke="none">{data.map((x,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip content={<ChartTip/>}/><Legend/></PieChart></ResponsiveContainer></div> }
export function MatrixChart({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top:18,right:18,bottom:18,left:18}}><CartesianGrid stroke={C.grid}/><XAxis type="number" dataKey="effort" name="Esforço" domain={[0,5]} tick={tick}/><YAxis type="number" dataKey="impact" name="Impacto" tick={tick}/><ZAxis range={[70,180]}/><Tooltip content={<ChartTip/>}/><Scatter data={data} fill={C.green}/></ScatterChart></ResponsiveContainer></div> }

export function BridgeChart({current=0,projected=0,items=[]}){
  let running=Number(current)||0
  const rows=[{name:'EBITDA Atual',base:0,step:running,display:running,type:'total'}]
  for(const item of items||[]){
    const delta=Number(item.impact)||0
    const next=running+delta
    rows.push({name:item.label,base:Math.min(running,next),step:Math.abs(delta),display:delta,type:delta>=0?'pos':'neg'})
    running=next
  }
  rows.push({name:'EBITDA Projetado',base:0,step:Number(projected)||running,display:Number(projected)||running,type:'total'})
  return <div className="chart chart-lg"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} margin={{top:18,right:12,left:10,bottom:42}}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="name" tick={{...tick,fontSize:9}} angle={-22} textAnchor="end" interval={0} height={72}/><YAxis tick={tick} tickFormatter={v=>`${(v/1e6).toLocaleString('pt-BR',{maximumFractionDigits:1})} mi`}/><Tooltip content={({active,payload,label})=>active&&payload?.length?<div className="chart-tip"><b>{label}</b><span>{Number(payload[0]?.payload?.display||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})}</span></div>:null}/><Bar dataKey="base" stackId="w" fill="transparent" isAnimationActive={false}/><Bar dataKey="step" stackId="w" radius={[4,4,0,0]} isAnimationActive={false}>{rows.map((r,i)=><Cell key={i} fill={r.type==='pos'?C.green:r.type==='neg'?C.red:C.blue}/>)}</Bar></BarChart></ResponsiveContainer></div>
}

// Gráficos derivados exclusivamente de registros já retornados pelo motor, sem séries sintéticas.
export function FamilyWeekChart({data=[]}){
 const families=[...new Set(data.map(r=>r.family))]; const weeks=[...new Set(data.map(r=>r.week))].sort();
 const rows=weeks.map(week=>({week,...Object.fromEntries(families.map(f=>[f,data.find(r=>r.family===f&&r.week===week)?.wape??null]))}));
 const palette=[C.blue,C.green,C.orange,C.purple,C.yellow,C.cyan];
 return <div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={rows} margin={{top:14,right:16,left:0,bottom:8}}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="week" tick={tick}/><YAxis tick={tick} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip content={<ChartTip/>}/><Legend/>{families.map((f,i)=><Line key={f} dataKey={f} name={f} type="monotone" stroke={palette[i%palette.length]} strokeWidth={2} dot={false} connectNulls={false}/>)}</LineChart></ResponsiveContainer></div>
}
export function PlantOeeEvolution({data=[]}){
 const plants=[...new Set(data.map(r=>r.plant))]; const periods=[...new Set(data.map(r=>r.period))];
 const rows=periods.map(period=>({period,...Object.fromEntries(plants.map(p=>[p,data.find(r=>r.plant===p&&r.period===period)?.oee??null]))}));
 const palette=[C.blue,C.green,C.orange,C.purple,C.yellow,C.cyan];
 return <div className="chart chart-lg"><ResponsiveContainer width="100%" height="100%"><LineChart data={rows} margin={{top:15,right:14,bottom:7,left:0}}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis domain={[0,1]} tick={tick} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip content={<ChartTip/>}/><Legend/><ReferenceLine y={.85} stroke={C.cyan} strokeDasharray="6 4"/>{plants.map((p,i)=><Line key={p} dataKey={p} type="monotone" stroke={palette[i%palette.length]} strokeWidth={2} dot={false}/>)}</LineChart></ResponsiveContainer></div>
}
export function FinanceTrendChart({data=[]}){
 return <div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:14,right:14,left:7,bottom:8}}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick} tickFormatter={v=>`${(v/1e6).toLocaleString('pt-BR',{maximumFractionDigits:1})} mi`}/><Tooltip content={<ChartTip/>}/><Legend/><Line dataKey="revenue" name="Receita Líquida" stroke={C.blue} strokeWidth={2.5} dot={false}/><Line dataKey="industrial_margin" name="Margem Industrial" stroke={C.green} strokeWidth={2.5} dot={false}/><Line dataKey="ebitda" name="EBITDA Gerencial" stroke={C.yellow} strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer></div>
}
export function MaterialsConsumptionChart({data=[]}){
 return <div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{top:14,right:12,left:10,bottom:8}}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick}/><Tooltip content={<ChartTip/>}/><Legend/><Bar dataKey="standard" name="Padrão (kg)" fill={C.cyan} radius={[3,3,0,0]}/><Bar dataKey="actual" name="Real (kg)" fill={C.orange} radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div>
}
