'use client'
import { ResponsiveContainer, LineChart, Line, BarChart, Bar, ComposedChart, CartesianGrid, XAxis, YAxis, Tooltip, Legend, ReferenceLine, PieChart, Pie, Cell, ScatterChart, Scatter, ZAxis } from 'recharts'

const C={blue:'#2d8cff',cyan:'#28c8ee',green:'#32d19a',orange:'#ff8d43',yellow:'#f2bb4f',red:'#f06464',purple:'#9d7cff',muted:'#6f8da1',grid:'#17364b'}
const tick={fill:'#8ea5b6',fontSize:11}
export const ChartTip=({active,payload,label})=> active&&payload?.length?<div className="chart-tip"><b>{label}</b>{payload.map((p,i)=><span key={i}>{p.name}: {typeof p.value==='number'?p.value.toLocaleString('pt-BR',{maximumFractionDigits:2}):p.value}</span>)}</div>:null
export function TrendChart({data,percent=true}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:10,right:14,left:0,bottom:2}}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick} domain={percent?[0,1]:['auto','auto']} tickFormatter={v=>percent?`${Math.round(v*100)}%`:v}/><Tooltip content={<ChartTip/>}/><Legend/><Line type="monotone" dataKey="oee" name="OEE" stroke={C.blue} strokeWidth={2.3} dot={false}/><Line type="monotone" dataKey="adherence" name="Aderência" stroke={C.green} strokeWidth={2.3} dot={false}/><Line type="monotone" dataKey="otif" name="OTIF" stroke={C.orange} strokeWidth={2.3} dot={false}/><Line type="monotone" dataKey="margin" name="Margem EBITDA" stroke={C.yellow} strokeWidth={2.3} dot={false}/></LineChart></ResponsiveContainer></div> }
export function HorizontalBars({data,dataKey='impact',nameKey='name',color=C.red,valueFormatter}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{top:2,right:20,left:20,bottom:2}}><CartesianGrid stroke={C.grid} horizontal={false}/><XAxis type="number" tick={tick}/><YAxis type="category" dataKey={nameKey} width={130} tick={tick}/><Tooltip content={<ChartTip/>}/><Bar dataKey={dataKey} fill={color} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div> }
export function HealthDonut({score,status=[]}){ const counts={good:status.filter(x=>x.state==='good').length,warn:status.filter(x=>x.state==='warn').length,bad:status.filter(x=>x.state==='bad').length}; const data=[{name:'Saudável',value:counts.good,color:C.green},{name:'Atenção',value:counts.warn,color:C.yellow},{name:'Crítico',value:counts.bad,color:C.red}].filter(x=>x.value>0); return <div className="health-wrap"><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.length?data:[{value:1,color:C.muted}]} dataKey="value" innerRadius="67%" outerRadius="91%" stroke="none">{(data.length?data:[{color:C.muted}]).map((e,i)=><Cell key={i} fill={e.color}/>)}</Pie></PieChart></ResponsiveContainer><div className="donut-center"><strong>{Math.round(score||0)}</strong><span>Saúde</span></div></div><div className="health-counts"><div><strong className="good">{counts.good}</strong><span>acima/meta</span></div><div><strong className="warn">{counts.warn}</strong><span>atenção</span></div><div><strong className="bad">{counts.bad}</strong><span>críticos</span></div></div></div> }
export function OeePlantChart({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{top:10,right:10,left:0,bottom:2}}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="plant" tick={tick}/><YAxis tick={tick} domain={[0,1]} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip content={<ChartTip/>}/><Legend/><ReferenceLine y={.85} stroke={C.cyan} strokeDasharray="6 5" label={{value:'Meta OEE 85%',fill:'#9ccfe0',fontSize:10}}/><Bar dataKey="oee" name="OEE" fill={C.blue} radius={[4,4,0,0]}/><Line type="monotone" dataKey="availability" name="Disponibilidade" stroke={C.cyan} strokeWidth={2}/><Line type="monotone" dataKey="performance" name="Performance" stroke={C.orange} strokeWidth={2}/><Line type="monotone" dataKey="quality" name="Qualidade" stroke={C.purple} strokeWidth={2}/></ComposedChart></ResponsiveContainer></div> }
export function SimpleBars({data,nameKey='plant',valueKey='production',color=C.blue}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{top:8,right:14,left:4,bottom:4}}><CartesianGrid stroke={C.grid} horizontal={false}/><XAxis type="number" tick={tick}/><YAxis type="category" dataKey={nameKey} width={100} tick={tick}/><Tooltip content={<ChartTip/>}/><Bar dataKey={valueKey} fill={color} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div> }
export function OeeTrend({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick} domain={[0,1]} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip content={<ChartTip/>}/><Legend/><ReferenceLine y={.85} stroke={C.cyan} strokeDasharray="5 5"/><Bar dataKey="oee" name="OEE" fill={C.blue}/><Line dataKey="availability" name="Disponibilidade" stroke={C.green}/><Line dataKey="performance" name="Performance" stroke={C.orange}/><Line dataKey="quality" name="Qualidade" stroke={C.purple}/></ComposedChart></ResponsiveContainer></div> }
export function ForecastChart({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick}/><Tooltip content={<ChartTip/>}/><Legend/><Bar dataKey="forecast" name="Forecast" fill={C.blue}/><Bar dataKey="plan" name="MRP / Plano" fill={C.green}/><Line dataKey="produced" name="Produzido" stroke={C.orange} strokeWidth={2.5}/></ComposedChart></ResponsiveContainer></div> }
export function CapacityChart({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis yAxisId="left" tick={tick}/><YAxis yAxisId="right" orientation="right" tick={tick} domain={[0,1]} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip content={<ChartTip/>}/><Legend/><Bar yAxisId="left" dataKey="capacity" name="Capacidade Nominal" fill="#7289a1"/><Bar yAxisId="left" dataKey="production" name="Produção Real" fill={C.blue}/><Line yAxisId="right" dataKey="utilization" name="Utilização" stroke={C.orange} strokeWidth={2.3}/></ComposedChart></ResponsiveContainer></div> }
export function ServiceChart({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><CartesianGrid stroke={C.grid} vertical={false}/><XAxis dataKey="period" tick={tick}/><YAxis tick={tick} domain={[0,1]} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip content={<ChartTip/>}/><Legend/><ReferenceLine y={.95} stroke={C.cyan} strokeDasharray="5 5"/><Bar dataKey="otif" name="OTIF" fill={C.blue}/><Line dataKey="on_time" name="On Time" stroke={C.cyan}/><Line dataKey="in_full" name="In Full" stroke={C.green}/></ComposedChart></ResponsiveContainer></div> }
export function CostDonut({data}){ const colors=[C.blue,C.orange,C.green,C.purple,C.yellow]; return <div className="chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius="55%" outerRadius="80%" stroke="none">{data.map((x,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip content={<ChartTip/>}/><Legend/></PieChart></ResponsiveContainer></div> }
export function MatrixChart({data}){ return <div className="chart"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top:18,right:18,bottom:18,left:18}}><CartesianGrid stroke={C.grid}/><XAxis type="number" dataKey="effort" name="Esforço" domain={[0,5]} tick={tick}/><YAxis type="number" dataKey="impact" name="Impacto" tick={tick}/><ZAxis range={[70,180]}/><Tooltip content={<ChartTip/>}/><Scatter data={data} fill={C.green}/></ScatterChart></ResponsiveContainer></div> }
