'use client'
import { Component, useEffect, useState } from 'react'
import Link from 'next/link'
import { useSearchParams } from 'next/navigation'
import Sidebar from './Sidebar'
import { getJSON } from '../lib/api'
import { PageHeader,KpiCard,Panel,DataTable,StatusBadge,IconBox,fmtMoney,fmtNumber,fmtPct,EmptyState } from './UI'
import { TrendChart,HorizontalBars,HealthDonut,MatrixChart,CostDonut,BridgeChart,OeePlantChart,SimpleBars,OeeTrend,ForecastChart,CapacityChart,ServiceChart,MultiPlantTrend,FamilyWeekChart,MaterialTrend,SupplierChart,FinanceTrend,PlantMap } from './Charts'

const meta={
 cockpit:['Cockpit Executivo','Panorama integrado da performance industrial e oportunidades de valor'],
 multiplantas:['Visão Multiplantas','Comparação planta a planta da performance industrial — sem OEE consolidado'],
 pcp:['PCP & Aderência','Forecast, planejamento e execução em uma única visão'],
 oee:['Produção & OEE','Desempenho da produção, perdas, ofensores e oportunidades de melhoria'],
 capacidade:['Capacidade','Potencial produtivo, restrições, demanda e valor monetizável'],
 materiais:['Materiais & Supply','Eficiência no uso de materiais e segurança no abastecimento'],
 logistica:['Logística','OTIF, frete, nível de serviço, pedidos críticos e receita em risco'],
 financas:['Finanças & DRE','Tradução da performance operacional em resultado financeiro'],
 diagnostico:['Diagnóstico','Da causa/evidência ao impacto e à recomendação executiva'],
 alavancas:['Alavancas de Valor','Simule alavancas, projete a DRE e reconcilie o EBITDA Gerencial'],
 'central-dados':['Central de Dados','Data Lake industrial, ingestão, qualidade e publicação da base ativa'],
 'plano-acao':['Plano de Ação','Transforme prioridades em execução, responsáveis, prazos e valor capturado'],
 agente:['Agente de Performance','Interprete a operação com contexto, evidência e impacto financeiro'],
 relatorios:['Relatórios','Relatórios executivos e operacionais do Industrial Performance'],
 mapeamentos:['Mapeamentos','Governança do DE/PARA inteligente por empresa e fonte'],
 'qualidade-dados':['Qualidade dos Dados','Completeza, consistência, linhagem e confiança da base industrial'],
 'meu-plano':['Meu Plano','Recursos disponíveis e evolução do produto'], ajuda:['Ajuda','Como ler e operar o Industrial Performance']
}
const ACTIVE_SCREENS=new Set(['multiplantas','cockpit','pcp','oee','capacidade','materiais','logistica','financas','diagnostico','alavancas','plano-acao','agente','relatorios','central-dados'])
const NO_PLANT=new Set(['multiplantas','central-dados'])

export default function DashboardClient({screen}){
 const search=useSearchParams(); const queryPlant=search.get('plant')
 const enabled=ACTIVE_SCREENS.has(screen)
 const [plants,setPlants]=useState([]); const [plant,setPlant]=useState(queryPlant||'Planta Campinas'); const [data,setData]=useState(null); const [err,setErr]=useState(''); const [loading,setLoading]=useState(enabled); const [reloadKey,setReloadKey]=useState(0)
 useEffect(()=>{ const saved=typeof window!=='undefined'?window.localStorage.getItem('ip_selected_plant'):null; if(queryPlant&&queryPlant!==plant)setPlant(queryPlant); else if(!queryPlant&&saved&&saved!==plant)setPlant(saved) },[queryPlant])
 useEffect(()=>{ if(typeof window!=='undefined'&&plant)window.localStorage.setItem('ip_selected_plant',plant) },[plant])
 useEffect(()=>{
   if(!enabled){setLoading(false);setData(null);return}
   let active=true; setLoading(true); setErr('')
   getJSON(`/api/bootstrap/${screen}?plant=${encodeURIComponent(plant)}`).then(x=>{if(!active)return;setPlants(x.plants||[]);if(x.plant&&x.plant!==plant&&!NO_PLANT.has(screen))setPlant(x.plant);setData(x.data||{})}).catch(e=>{if(active)setErr(String(e))}).finally(()=>{if(active)setLoading(false)})
   return()=>{active=false}
 },[screen,plant,reloadKey,enabled])
 const [title,subtitle]=meta[screen]||[screen,'Módulo do Industrial Performance']
 return <div className="app-shell"><Sidebar/><main className="main"><div className="page">
   <PageHeader title={title} subtitle={subtitle} plant={enabled&&!NO_PLANT.has(screen)?plant:undefined} setPlant={setPlant} plants={plants}/>
   {!enabled?<EmptyState title={`${title} — no radar`} text="A tela permanece no roadmap e só será liberada quando conteúdo, matemática, dados, interação e causalidade estiverem fechados."/>:
    loading?<div className="empty-state compact-loader"><h2>Carregando dados…</h2><p>Conectando ao motor Industrial Performance.</p></div>:
    err?<div className="empty-state"><h2>Não foi possível carregar os dados</h2><p>{err}</p><button className="control-btn control-primary" onClick={()=>setReloadKey(k=>k+1)}>Tentar novamente</button></div>:
    <RuntimeBoundary key={`${screen}-${plant}-${reloadKey}`}><Screen screen={screen} data={data} plant={plant}/></RuntimeBoundary>
   }
   <div className="footer-note">Industrial Performance v1.0.7 • Visual + Analytical Polish • dados, análises, drill-down e reconciliações em validação</div>
 </div></main></div>
}


class RuntimeBoundary extends Component{
 constructor(props){super(props);this.state={error:null}}
 static getDerivedStateFromError(error){return {error}}
 componentDidCatch(error,info){if(typeof console!=='undefined')console.error('Industrial Performance runtime error',error,info)}
 render(){if(this.state.error)return <div className="empty-state runtime-error"><h2>Erro de renderização isolado</h2><p>{String(this.state.error?.message||this.state.error)}</p><p>A navegação e o restante do aplicativo permanecem disponíveis. Esta tela precisa de correção antes de ser promovida.</p></div>;return this.props.children}
}

function Screen({screen,data,plant}){ const map={multiplantas:Multiplantas,cockpit:Cockpit,pcp:PCP,oee:OEE,capacidade:Capacidade,materiais:Materiais,logistica:Logistica,financas:Financas,diagnostico:Diagnostico,alavancas:Alavancas,'plano-acao':PlanoAcao,agente:Agente,relatorios:Relatorios,'central-dados':CentralDados}; const C=map[screen]; return C?<C data={data} plant={plant}/>:<EmptyState/> }
function Drill({href,children}){return href?<Link className="drill-link" href={href}>{children} →</Link>:<span>{children}</span>}
function AnalysisList({items=[]}){return <div className="analysis-list">{items.map((x,i)=><div className="analysis-card" key={i}><strong>{i+1}. {x.title}</strong><span>{x.text}</span></div>)}</div>}
function RecommendationList({items=[]}){return <div className="alert-list">{items.map((x,i)=><div className="alert" key={i}><span className="alert-dot good-dot">{x.priority||i+1}</span><div><b>{x.action}</b>{x.problem&&<span>{x.problem}</span>}</div>{x.path&&<Drill href={x.path}>Abrir</Drill>}</div>)}</div>}

function ExecutiveConclusion({data}){if(!data)return null;return <div className="executive-conclusion"><strong>{data.headline||'Conclusão executiva'}</strong><p>{data.text}</p><div className="conclusion-decision"><span>Decisão recomendada</span><b>{data.decision}</b></div>{data.confidence&&<div className="data-note">Confiança da leitura: {data.confidence}</div>}</div>}
function drillImpact(x){const l=String(x?.impact_label||'').toLowerCase();const v=x?.impact;if(v===null||v===undefined)return '—';if(l.includes('r$')||l.includes('receita')||l.includes('ebitda')||l.includes('impacto / risco'))return fmtMoney(v);if(l.includes('margem'))return fmtPct(v);if(l.includes('gap'))return `${fmtNumber(Number(v)*100,1)} p.p.`;return fmtNumber(v)}
function DrilldownTable({items=[]}){return <DataTable rows={items} columns={[{key:'level',label:'Nível'},{key:'offender',label:'Ofensor / recorte'},{key:'evidence',label:'Evidência'},{key:'impact',label:'Impacto / exposição',render:(v,r)=><span>{drillImpact(r)}{r.impact_label?` · ${r.impact_label}`:''}</span>},{key:'path',label:'Aprofundar',render:v=>v?<Drill href={v}>Abrir</Drill>:'—'}]}/>}

function Multiplantas({data}){
 const c=data.cards||{},rows=data.plants||[]
 return <><div className="kpi-grid cols-6"><KpiCard label="Plantas monitoradas" value={c.plants||0} foot="comparação individual" icon="▦"/><KpiCard label="Menor OEE" value={fmtPct(c.worst?.oee)} foot={c.worst?.plant||'—'} state="bad" icon="◉"/><KpiCard label="Melhor OEE" value={fmtPct(c.best?.oee)} foot={c.best?.plant||'—'} state="good" icon="◉"/><KpiCard label="Produção Total" value={fmtNumber(c.production)} foot="somatório de unidades" icon="▥"/><KpiCard label="Receita Líquida Grupo" value={fmtMoney(c.revenue)} foot="somatório financeiro" icon="▮"/><KpiCard label="EBITDA Gerencial Grupo" value={fmtMoney(c.ebitda)} foot="somatório financeiro; OEE não consolidado" icon="▮"/></div>
 <div className="grid grid-12">
  <Panel className="span-6" title="OEE por Planta" subtitle="Comparação individual de OEE, Disponibilidade, Performance e Qualidade; meta 85%." tag="SEM CONSOLIDAR" icon="◉"><OeePlantChart data={rows}/></Panel>
  <Panel className="span-3" title="Produção por Planta" subtitle="Volume realizado no período." icon="▥"><SimpleBars data={rows}/></Panel>
  <Panel className="span-3" title="Custo de Conversão por Planta" subtitle="Mesma definição gerencial em todas as plantas." icon="▮"><SimpleBars data={rows} valueKey="conversion_cost" statusMode/></Panel>
  <Panel className="span-8" title="Indicadores por Planta" subtitle="Produção, OEE, componentes, custo e tendência." tag="DRILL-THROUGH" icon="▤"><DataTable rows={rows} columns={[{key:'plant',label:'Planta',render:(v,r)=><Drill href={r.drilldown}>{v}</Drill>},{key:'production',label:'Produção',render:v=>fmtNumber(v)},{key:'production_change',label:'Δ volume',render:v=>v===null?'—':fmtPct(v)},{key:'oee',label:'OEE',render:v=>fmtPct(v)},{key:'availability',label:'Disp.',render:v=>fmtPct(v)},{key:'performance',label:'Performance',render:v=>fmtPct(v)},{key:'quality',label:'Qualidade',render:v=>fmtPct(v)},{key:'conversion_cost',label:'Custo Conv.',render:v=>fmtMoney(v)}]}/></Panel>
  <Panel className="span-4" title="Mapa das Plantas" subtitle="Localização das unidades monitoradas e status de OEE." tag="BRASIL" icon="⌖"><PlantMap data={rows} locations={data.locations||[]}/><div className="data-note">Coordenadas usadas apenas para plantas cujo nome identifica inequivocamente a cidade no cadastro demo aprovado.</div></Panel>
  <Panel className="span-8" title="Evolução do OEE por planta" subtitle="Cada planta é uma série própria; recalculado por período." tag="12 MESES" icon="▦"><MultiPlantTrend data={data.evolution||[]}/></Panel>
  <Panel className="span-4" title="Principais insights" subtitle="Diferenças, deteriorações e prioridade de aprofundamento." icon="◆"><AnalysisList items={data.insights||[]}/></Panel>
  <Panel className="span-5" title="Conclusão executiva" subtitle="Qual planta exige atenção primeiro e por quê." tag="DECISÃO" icon="▤"><ExecutiveConclusion data={data.executive_conclusion}/></Panel>
  <Panel className="span-7" title="Drill-down por planta" subtitle="Da comparação do grupo para o Cockpit da planta selecionada." tag="PLANTA → COCKPIT" icon="⌕"><DrilldownTable items={data.drilldowns||[]}/></Panel>
  <Panel className="span-12" title="Recomendações e drill-through" subtitle="O clique na planta abre o Cockpit no contexto correto." icon="◎"><RecommendationList items={data.recommendations||[]}/></Panel>
 </div></>
}

function Cockpit({data}){
 const k=data.kpis||{},opp=data.opportunities||[],health=data.health||{}
 return <><div className="kpi-grid cols-6"><KpiCard label="Produção Real" value={fmtNumber(k.production)} foot="unidades no período" icon="▥"/><KpiCard label="OEE" value={fmtPct(k.oee)} foot="Meta 85%" state={k.oee>=.85?'good':'bad'} icon="◉"/><KpiCard label="Aderência (Prod./Plano)" value={fmtPct(k.adherence)} foot="Meta 98%" state={k.adherence>=.98?'good':'bad'} icon="◎"/><KpiCard label="Custo de Conversão" value={fmtMoney(k.conversion_cost)} foot="por unidade" icon="▮"/><KpiCard label="EBITDA Gerencial" value={fmtMoney(k.ebitda)} foot={`${fmtPct(k.ebitda_margin)} da receita`} state="good" icon="▮"/><KpiCard label="OTIF" value={fmtPct(k.otif)} foot="Meta 95%" state={k.otif>=.95?'good':'bad'} icon="◎"/></div>
 <div className="grid grid-12">
  <Panel className="span-6" title="Evolução do OEE e seus componentes" subtitle="OEE em barras; Disponibilidade, Performance e Qualidade em linhas. Meta OEE 85%." tag="MENSAL" icon="▦"><OeeTrend data={data.series||[]}/></Panel>
  <Panel className="span-3" title="Onde está o dinheiro?" subtitle="Pareto financeiro reconciliável com o Diagnóstico." tag="IMPACTO DIRETO" icon="▮"><HorizontalBars data={opp} dataKey="impact" nameKey="name"/><div className="total-strip"><span>Total sem dupla contagem</span><strong>{fmtMoney(data.money_total)}</strong></div></Panel>
  <Panel className="span-3" title="Saúde da Operação" subtitle="OEE 35%, PCP 20%, Capacidade 15%, Materiais 15%, OTIF 15%." tag="PONDERADO" icon="♥"><HealthDonut score={health.score} status={health.status}/><div className="weight-list">{health.status?.map((x,i)=><div key={i}><span>{x.name} · {fmtPct(x.weight,0)}</span><b>{fmtPct(x.value)}</b></div>)}</div></Panel>
  <Panel className="span-6" title="Performance por pilar" subtitle="Atual × meta/referência; clique para aprofundar." tag="ATUAL × META" icon="◉"><div className="pillar-grid">{data.pillar?.map((x,i)=>{const v=x.value||0;return <Link href={x.path||'#'} className="pillar" key={i}><div className="pillar-track"><div className="pillar-bar" style={{height:`${Math.max(6,Math.min(100,v*100))}%`}}/></div><strong>{fmtPct(v)}</strong><span>{x.name}</span></Link>})}</div></Panel>
  <Panel className="span-3" title="Top 5 oportunidades" subtitle="Impactos diretos únicos; clique para aprofundar." tag="DRILL-DOWN" icon="◆"><div className="opportunity-list">{opp.slice(0,5).map((x,i)=><Link href={x.path||'#'} className="opportunity" key={i}><span className="num">{i+1}</span><div className="opportunity-copy"><b>{x.name}</b><span>{x.pillar}</span></div><strong>{fmtMoney(x.impact)}</strong></Link>)}</div></Panel>
  <Panel className="span-3" title="Alertas prioritários" subtitle="KPI, gap e destino de aprofundamento." icon="!"><div className="alert-list">{(data.alerts||[]).slice(0,5).map((x,i)=><div className="alert" key={i}><span className="alert-dot">!</span><div><b>{x.kpi} fora da referência</b><span>Atual {fmtPct(x.value)} · meta {fmtPct(x.target)} · gap {fmtPct(x.gap)}</span></div><Drill href={x.path}>Abrir</Drill></div>)}</div></Panel>
  <Panel className="span-5" title="Produção da planta por linha" subtitle="Volume e OEE no contexto da planta selecionada." icon="▥"><DataTable rows={data.production_detail||[]} columns={[{key:'line',label:'Linha'},{key:'production',label:'Produção',render:v=>fmtNumber(v)},{key:'oee',label:'OEE',render:v=>fmtPct(v)},{key:'availability',label:'Disp.',render:v=>fmtPct(v)},{key:'performance',label:'Perf.',render:v=>fmtPct(v)},{key:'quality',label:'Qual.',render:v=>fmtPct(v)}]}/></Panel>
  <Panel className="span-4" title="Receita, Custos e EBITDA Gerencial" subtitle="Série mensal da planta selecionada." icon="▮"><FinanceTrend data={data.finance_trend||[]}/></Panel>
  <Panel className="span-3" title="Resumo executivo" subtitle="Situação, gaps e foco recomendado." tag="C-LEVEL" icon="▤"><div className="executive-copy">{data.executive?.summary}</div></Panel>
  <Panel className="span-4" title="Principais insights" subtitle="Leituras que explicam a prioridade executiva." icon="◆"><AnalysisList items={data.insights||[]}/></Panel>
  <Panel className="span-4" title="Conclusão executiva" subtitle="Síntese para decisão 30/60/90 dias." tag="DECISÃO" icon="◎"><ExecutiveConclusion data={data.executive_conclusion}/></Panel>
  <Panel className="span-4" title="Drill-down executivo" subtitle="Oportunidade/alerta → módulo responsável → evidência." tag="RASTREÁVEL" icon="⌕"><DrilldownTable items={data.drilldowns||[]}/></Panel>
  <Panel className="span-12" title="Ações prioritárias" subtitle="Recomendações derivadas do Diagnóstico; valor só é capturado após execução." tag="30/60/90" icon="✓"><RecommendationList items={data.actions||[]}/></Panel>
 </div></>
}

function PCP({data}){
 const m=data.metrics||{},money=data.money||{}
 return <><div className="kpi-grid cols-4"><KpiCard label="Forecast" value={fmtNumber(m.forecast)} foot="unidades" icon="▥"/><KpiCard label="MRP / Plano" value={fmtNumber(m.plan)} foot="unidades" icon="▦"/><KpiCard label="Produzido" value={fmtNumber(m.produced)} foot="unidades" icon="▥"/><KpiCard label="Aderência (Produzido / Plano)" value={fmtPct(m.adherence)} foot="Meta 98%" state={m.adherence>=.98?'good':'bad'} icon="◎"/></div>
 <Panel title="Qualidade do Forecast" subtitle="MAPE, WAPE e Bias com definição, interpretação, vantagem e limitação." tag="REGRAS DE ZERO" icon="◎"><div className="grid grid-12"><div className="span-3 metric-box"><span>MAPE</span><strong>{fmtPct(m.mape)}</strong><p>{data.rules?.mape}</p></div><div className="span-3 metric-box"><span>WAPE</span><strong>{fmtPct(m.wape)}</strong><p>{data.rules?.wape}</p></div><div className="span-3 metric-box"><span>Bias</span><strong>{fmtPct(m.bias)}</strong><p>{data.rules?.bias}</p></div><div className="span-3 metric-box"><span>Leitura executiva</span><strong>{(m.bias||0)>0?'Sobreprevisão':(m.bias||0)<0?'Subprevisão':'Sem viés'}</strong><p>WAPE é a principal leitura consolidada; MAPE não usa casos Real=0.</p></div></div></Panel>
 <div className="grid grid-12">
  <Panel className="span-6" title="Forecast × Plano × Produzido" subtitle="Distingue gap de planejamento e gap de execução." tag="MENSAL" icon="◎"><ForecastChart data={data.monthly||[]}/></Panel>
  <Panel className="span-6" title="Acurácia do Forecast por Família" subtitle="WAPE por família e semana." tag="FAMÍLIA × SEMANA" icon="◎"><FamilyWeekChart data={data.family_week||[]}/></Panel>
  <Panel className="span-6" title="Acurácia por Família" subtitle="MAPE, WAPE, Bias e tendência por família." tag="FAMÍLIA × PERÍODO" icon="▤"><DataTable rows={data.family_month||[]} columns={[{key:'family',label:'Família'},{key:'mape',label:'MAPE',render:v=>fmtPct(v)},{key:'wape',label:'WAPE',render:v=>fmtPct(v)},{key:'bias',label:'Bias',render:v=>fmtPct(v)},{key:'adherence',label:'Aderência',render:v=>fmtPct(v)}]}/></Panel>
  <Panel className="span-6" title="Acurácia por Planta" subtitle="Recalculada a partir dos dados, não média de percentuais." tag="PLANTA × PERÍODO" icon="▤"><DataTable rows={data.plant_month||[]} columns={[{key:'plant',label:'Planta'},{key:'mape',label:'MAPE',render:v=>fmtPct(v)},{key:'wape',label:'WAPE',render:v=>fmtPct(v)},{key:'bias',label:'Bias',render:v=>fmtPct(v)},{key:'adherence',label:'Aderência',render:v=>fmtPct(v)}]}/></Panel>
  <Panel className="span-5" title="Principais ofensores (SKU)" subtitle="Contribuição ao WAPE, Bias, erro absoluto e gap de execução." tag="DRILL-DOWN" icon="!"><DataTable rows={data.offenders||[]} columns={[{key:'sku',label:'SKU'},{key:'family',label:'Família'},{key:'wape_contribution',label:'Contrib. WAPE',render:v=>fmtPct(v)},{key:'bias',label:'Bias',render:v=>fmtPct(v)},{key:'abs_error',label:'Erro abs.',render:v=>fmtNumber(v)},{key:'execution_gap_units',label:'Gap plano',render:v=>fmtNumber(v)}]}/></Panel>
  <Panel className="span-3" title="Onde está o dinheiro?" subtitle="Risco valorizado somente quando a base permite." icon="▮"><div className="money-list"><Money label="Demanda confirmada não atendida" value={money.confirmed_demand_margin_risk} foot={`${fmtNumber(money.confirmed_demand_short_units)} un · margem em risco`}/><Money label="Sobreprevisão" value={null} foot={`${fmtNumber(money.overforecast_units)} un · custo específico N/D`}/><Money label="Demanda não prevista" value={null} foot={`${fmtNumber(money.unexpected_units)} un · custo específico N/D`}/></div><div className="data-note">{money.note}</div></Panel>
  <Panel className="span-4" title="Insights e recomendações" subtitle="Da acurácia ao foco de gestão." icon="◆"><AnalysisList items={data.insights||[]}/><div className="separator"/><RecommendationList items={data.recommendations||[]}/></Panel>
  <Panel className="span-4" title="Conclusão executiva" subtitle="Forecast, plano e execução traduzidos em prioridade." tag="DECISÃO" icon="▤"><ExecutiveConclusion data={data.executive_conclusion}/></Panel>
  <Panel className="span-5" title="Drill-down de ofensores" subtitle="SKU → família → erro → gap de execução → Diagnóstico." tag="SKU" icon="⌕"><DrilldownTable items={data.drilldowns||[]}/></Panel>
  <Panel className="span-3" title="Boas práticas de Forecast e PCP" subtitle="Rotina gerencial permanente, não tutorial genérico." icon="✓"><div className="practice-list">{(data.management_practices||[]).map((x,i)=><div className="practice-item" key={i}><span>{i+1}</span><b>{x}</b></div>)}</div></Panel>
 </div></>
}

function OEE({data}){
 const k=data.kpis||{},t=data.targets||{},money=data.money||{}
 return <><div className="kpi-grid cols-6"><KpiCard label="OEE" value={fmtPct(k.oee)} foot={`Meta ${fmtPct(t.oee)}`} state={k.oee>=t.oee?'good':'bad'} icon="◉"/><KpiCard label="Disponibilidade" value={fmtPct(k.availability)} foot={`Meta ${fmtPct(t.availability)}`} state={k.availability>=t.availability?'good':'bad'} icon="◴"/><KpiCard label="Performance" value={fmtPct(k.performance)} foot={`Meta ${fmtPct(t.performance)}`} state={k.performance>=t.performance?'good':'bad'} icon="↗"/><KpiCard label="Qualidade" value={fmtPct(k.quality)} foot={`Meta ${fmtPct(t.quality)}`} state={k.quality>=t.quality?'good':'bad'} icon="◇"/><KpiCard label="Produção Real" value={fmtNumber(k.production)} foot="unidades" icon="▥"/><KpiCard label="Impacto Financeiro" value={fmtMoney(k.impact)} foot="impacto direto + margem em risco demand-backed" state="bad" icon="▮"/></div>
 <div className="grid grid-12">
  <Panel className="span-8" title="Evolução do OEE e seus componentes" subtitle="OEE em barras; Disponibilidade, Performance e Qualidade em linhas." tag="MENSAL" icon="◉"><OeeTrend data={data.trend||[]}/></Panel>
  <Panel className="span-4" title="Perdas por Equipamento — Top 10" subtitle="Tempo perdido, causa/evidência e parcela da perda de disponibilidade." tag="DRILL-DOWN" icon="▦"><DataTable rows={data.equipment||[]} columns={[{key:'equipment',label:'Equipamento'},{key:'hours',label:'Horas',render:v=>fmtNumber(v,1)},{key:'cause',label:'Causa'},{key:'evidence',label:'Evidência'},{key:'impact',label:'Impacto',render:v=>fmtMoney(v)}]}/></Panel>
  <Panel className="span-4" title="Ofensores de Disponibilidade" subtitle="Eventos de parada com evidência e impacto alocado." icon="◴"><DataTable rows={data.availability_offenders||[]} columns={[{key:'cause',label:'Causa'},{key:'hours',label:'Horas',render:v=>fmtNumber(v,1)},{key:'share',label:'%',render:v=>fmtPct(v)},{key:'evidence',label:'Evidência'},{key:'impact',label:'Impacto',render:v=>fmtMoney(v)}]}/></Panel>
  <Panel className="span-4" title="Ofensores de Performance" subtitle="Perda de velocidade medida por linha." icon="↗"><DataTable rows={data.performance_offenders||[]} columns={[{key:'cause',label:'Ofensor'},{key:'units',label:'Unid. equivalentes',render:v=>fmtNumber(v)},{key:'share',label:'%',render:v=>fmtPct(v)},{key:'impact',label:'Impacto',render:v=>fmtMoney(v)}]}/></Panel>
  <Panel className="span-4" title="Ofensores de Qualidade" subtitle="Refugo monetizado por MP; retrabalho visível sem custo inventado." icon="◇"><DataTable rows={data.quality_offenders||[]} columns={[{key:'cause',label:'Produto'},{key:'scrap',label:'Refugo',render:v=>fmtNumber(v)},{key:'rework',label:'Retrabalho',render:v=>fmtNumber(v)},{key:'impact',label:'Impacto',render:v=>fmtMoney(v)}]}/></Panel>
  <Panel className="span-6" title="OEE por Linha" subtitle="OEE e componentes por linha para priorizar drill-down." icon="▤"><DataTable rows={data.lines||[]} columns={[{key:'line',label:'Linha'},{key:'production',label:'Produção',render:v=>fmtNumber(v)},{key:'oee',label:'OEE',render:v=>fmtPct(v)},{key:'availability',label:'Disp.',render:v=>fmtPct(v)},{key:'performance',label:'Performance',render:v=>fmtPct(v)},{key:'quality',label:'Qualidade',render:v=>fmtPct(v)}]}/></Panel>
  <Panel className="span-3" title="Onde está o dinheiro?" subtitle="Componentes exclusivos; OEE não é somado novamente." tag="SEM DUPLA CONTAGEM" icon="▮"><div className="money-list">{(money.items||[]).map((x,i)=><Money key={i} label={x.name} value={x.value} foot={`${fmtNumber(x.units)} un · ${x.evidence}`}/>)}</div><div className="total-strip"><span>Total identificado</span><strong>{fmtMoney(money.total)}</strong></div></Panel>
  <Panel className="span-3" title="Principais insights" subtitle="Leitura dos gaps, ofensores e regra financeira." icon="◆"><AnalysisList items={data.insights||[]}/></Panel>
  <Panel className="span-5" title="Conclusão executiva" subtitle="Gap de OEE, componente dominante e ofensor prioritário." tag="DECISÃO" icon="▤"><ExecutiveConclusion data={data.executive_conclusion}/></Panel>
  <Panel className="span-7" title="Drill-down de perdas" subtitle="Equipamento/componente → causa/evidência → Diagnóstico." tag="OEE → CAUSA" icon="⌕"><DrilldownTable items={data.drilldowns||[]}/></Panel>
  <Panel className="span-12" title="Ações recomendadas" subtitle="Derivadas dos ofensores e das evidências; Manutenção é causa/fonte, não módulo." icon="✓"><RecommendationList items={data.recommendations||[]}/></Panel>
 </div></>
}

function Capacidade({data}){
 const k=data.kpis||{},m=data.money||{}
 return <><div className="kpi-grid cols-5"><KpiCard label="Capacidade Nominal" value={fmtNumber(k.capacity)} foot="unidades no período" icon="▥"/><KpiCard label="Produção Real" value={fmtNumber(k.production)} foot="unidades" icon="▥"/><KpiCard label="Utilização da Capacidade" value={fmtPct(k.utilization)} foot="real / nominal" state={k.utilization>=.8?'good':'bad'} icon="◉"/><KpiCard label="Capacidade Ociosa" value={fmtNumber(k.idle)} foot={`${fmtPct(k.idle/k.capacity)} da capacidade`} icon="▦"/><KpiCard label="Potencial até 80%" value={fmtNumber(k.potential)} foot="unidades adicionais" state="good" icon="↗"/></div>
 <div className="grid grid-12">
  <Panel className="span-7" title="Capacidade, Produção e Utilização" subtitle="Nominal × Real + utilização ao longo do tempo." tag="MENSAL" icon="▦"><CapacityChart data={data.monthly||[]}/></Panel>
  <Panel className="span-5" title="Utilização por Linha / Recurso" subtitle="Drill-down de utilização e capacidade por recurso." tag="RECURSO" icon="▤"><DataTable rows={data.resources||[]} columns={[{key:'resource',label:'Recurso'},{key:'line',label:'Linha'},{key:'utilization',label:'Utilização',render:v=>fmtPct(v)},{key:'capacity',label:'Capacidade',render:v=>fmtNumber(v)},{key:'status',label:'Status',render:v=><StatusBadge state={v==='Gargalo'?'bad':v==='Atenção'?'warn':'good'}>{v}</StatusBadge>} ]}/></Panel>
  <Panel className="span-4" title="Cenários de Utilização" subtitle="Atual, 75%, 80%, 85% e 90%; sem converter automaticamente em EBITDA." icon="↗"><DataTable rows={data.scenarios||[]} columns={[{key:'utilization',label:'Utilização',render:v=>fmtPct(v)},{key:'production',label:'Produção',render:v=>fmtNumber(v)},{key:'gain',label:'Ganho vs. atual',render:v=>fmtNumber(v)}]}/></Panel>
  <Panel className="span-4" title="Gargalo da Capacidade" subtitle="Recurso com maior utilização/status na base." icon="!"><div className="metric-box"><span>Recurso prioritário</span><strong>{data.bottleneck?.resource||'—'}</strong><p>{data.bottleneck?.line||'—'} · Utilização {fmtPct(data.bottleneck?.utilization)} · Status {data.bottleneck?.status||'—'}</p></div></Panel>
  <Panel className="span-4" title="Perdas / composição da ociosidade" subtitle="A soma fecha exatamente a capacidade ociosa." icon="▦"><DataTable rows={data.losses||[]} columns={[{key:'cause',label:'Componente'},{key:'units',label:'Unidades',render:v=>fmtNumber(v)},{key:'share',label:'% ociosidade',render:v=>fmtPct(v)}]}/></Panel>
  <Panel className="span-4" title="Utilização por Turno" subtitle="Exibir somente quando houver granularidade na base." tag="DADO NECESSÁRIO" icon="◴"><div className="no-data-block"><strong>Não disponível</strong><p>{data.shift_message}</p></div></Panel>
  <Panel className="span-4" title="Onde está o dinheiro?" subtitle="Ociosa → recuperável → demanda → monetizável → impacto." tag="DEMAND-BACKED" icon="▮"><div className="money-list"><Money label="Capacidade ociosa" value={null} foot={`${fmtNumber(m.idle)} un`}/><Money label="Tecnicamente recuperável" value={null} foot={`${fmtNumber(m.recoverable)} un`}/><Money label="Volume monetizável" value={null} foot={`${fmtNumber(m.monetizable)} un`}/><Money label="Impacto financeiro potencial" value={m.impact} foot={`Margem industrial R$ ${fmtNumber(m.margin_unit,2)}/un`}/></div></Panel>
  <Panel className="span-4" title="Principais insights" subtitle="Restrição, capacidade recuperável e demanda." icon="◆"><AnalysisList items={data.insights||[]}/></Panel>
  <Panel className="span-4" title="Conclusão executiva" subtitle="Capacidade física não é valor até existir demanda e remoção da restrição." tag="DECISÃO" icon="▤"><ExecutiveConclusion data={data.executive_conclusion}/></Panel>
  <Panel className="span-4" title="Ações recomendadas" subtitle="Sequência coerente com gargalo e monetização." icon="✓"><RecommendationList items={data.recommendations||[]}/></Panel>
  <Panel className="span-12" title="Drill-down por recurso" subtitle="Recurso → utilização/status → capacidade → Diagnóstico." tag="RECURSO" icon="⌕"><DrilldownTable items={data.drilldowns||[]}/></Panel>
 </div></>
}

function Materiais({data}){
 const k=data.kpis||{},money=data.money||{}
 return <><div className="kpi-grid cols-6"><KpiCard label="Consumo Padrão" value={`${fmtNumber(k.standard_unit,2)} kg/un`} foot="padrão da base" icon="▦"/><KpiCard label="Consumo Real" value={`${fmtNumber(k.actual_unit,2)} kg/un`} foot="realizado" state={k.actual_unit<=k.standard_unit?'good':'bad'} icon="▥"/><KpiCard label="Desvio de MP" value={fmtMoney(k.deviation_value)} foot="consumo acima do padrão" state="bad" icon="▮"/><KpiCard label="Cobertura de Estoque" value={`${fmtNumber(k.coverage,0)} dias`} foot="média dos materiais" icon="▦"/><KpiCard label="Materiais Críticos" value={fmtNumber(k.critical)} foot="registros com risco alto" state={k.critical?'bad':'good'} icon="!"/><KpiCard label="Aderência de Fornecedores" value={fmtPct(k.supplier_adherence)} foot="média do período" state={k.supplier_adherence>=.95?'good':'warn'} icon="◎"/></div>
 <div className="section-band"><strong>Materiais</strong><span>Consumo eficiente, menos perdas, mais resultado.</span></div>
 <div className="grid grid-12">
  <Panel className="span-4" title="Consumo Padrão × Consumo Real" subtitle="kg/un por competência, calculado com produção real." icon="▥"><MaterialTrend data={data.monthly||[]}/></Panel>
  <Panel className="span-4" title="R$ perdido por material / família" subtitle="Pareto do desvio de consumo valorizado por preço real." icon="▮"><HorizontalBars data={(data.materials||[]).slice(0,8)} dataKey="impact" nameKey="material"/></Panel>
  <Panel className="span-4" title="Ofensores de Materiais" subtitle="Desvio, impacto, evidência e lacuna causal explícita." tag="DRILL-DOWN" icon="!"><DataTable rows={(data.materials||[]).slice(0,8)} columns={[{key:'material',label:'Material'},{key:'family',label:'Família'},{key:'deviation',label:'Desvio',render:v=>fmtPct(v)},{key:'impact',label:'Impacto',render:v=>fmtMoney(v)},{key:'possible_cause',label:'Causa / dado'}]}/></Panel>
  <Panel className="span-12" title="Onde está o dinheiro — Materiais" subtitle="Impactos diretos separados de capital e risco." tag="SEM DUPLA CONTAGEM" icon="▮"><div className="metric-trio"><div className="metric-box"><span>Consumo em excesso</span><strong>{fmtMoney(money.material_excess)}</strong><p>impacto direto de MP</p></div><div className="metric-box"><span>Compras emergenciais</span><strong>{fmtMoney(money.emergency)}</strong><p>impacto direto registrado</p></div><div className="metric-box"><span>Estoque em excesso</span><strong>{fmtMoney(money.excess_inventory)}</strong><p>capital de giro, fora do EBITDA</p></div></div></Panel>
 </div>
 <div className="section-band"><strong>Supply</strong><span>Cobertura, fornecedores e riscos para garantir continuidade.</span></div>
 <div className="grid grid-12">
  <Panel className="span-4" title="Cobertura por Material Crítico" subtitle="Cobertura contra lead time e risco cadastrado." icon="▦"><DataTable rows={(data.supply||[]).slice(0,10)} columns={[{key:'material',label:'Material'},{key:'supplier',label:'Fornecedor'},{key:'coverage',label:'Cobertura',render:v=>`${fmtNumber(v)} d`},{key:'lead_time',label:'Lead time',render:v=>`${fmtNumber(v)} d`},{key:'risk',label:'Risco',render:v=><StatusBadge state={v==='Alto'?'bad':v==='Médio'||v==='Medio'?'warn':'good'}>{v}</StatusBadge>}]}/></Panel>
  <Panel className="span-4" title="Lead Time × Aderência de Fornecedores" subtitle="Fornecedor/material com status real." icon="◎"><SupplierChart data={data.supply||[]}/></Panel>
  <Panel className="span-4" title="Riscos de Supply" subtitle="Risco, cobertura, evidência e impacto potencial na produção." icon="!"><DataTable rows={(data.supply||[]).slice(0,8)} columns={[{key:'material',label:'Material'},{key:'supplier',label:'Fornecedor'},{key:'risk',label:'Risco'},{key:'production_risk_units',label:'Produção em risco',render:v=>fmtNumber(v)},{key:'evidence',label:'Evidência'}]}/></Panel>
  <Panel className="span-4" title="Onde está o dinheiro — Supply" subtitle="Direto, risco e capital de giro separados." icon="▮"><div className="money-list"><Money label="Compras emergenciais" value={money.emergency} foot="custo registrado"/><Money label="Produção em risco" value={money.production_margin_risk} foot={`${fmtNumber(money.production_risk_units)} un · margem em risco`}/><Money label="Estoque em excesso" value={money.excess_inventory} foot="capital de giro; fora EBITDA"/></div></Panel>
  <Panel className="span-8" title="Insights executivos e recomendações" subtitle="Prioridades com evidência; causa de consumo não é inventada." icon="◆"><div className="grid grid-12"><div className="span-6"><AnalysisList items={data.insights||[]}/></div><div className="span-6"><RecommendationList items={data.recommendations||[]}/></div></div></Panel>
  <Panel className="span-5" title="Conclusão executiva" subtitle="Desvio de consumo, risco de abastecimento e dinheiro separados." tag="DECISÃO" icon="▤"><ExecutiveConclusion data={data.executive_conclusion}/></Panel>
  <Panel className="span-7" title="Drill-down de Materiais & Supply" subtitle="Material/fornecedor → evidência → impacto/risco → Diagnóstico." tag="MATERIAL → FORNECEDOR" icon="⌕"><DrilldownTable items={data.drilldowns||[]}/></Panel>
 </div></>
}

function Logistica({data}){
 const k=data.kpis||{},money=data.money||{}
 return <><div className="kpi-grid cols-6"><KpiCard label="OTIF" value={fmtPct(k.otif)} foot="Meta 95%" state={k.otif>=.95?'good':'bad'} icon="◎"/><KpiCard label="Frete por unidade" value={fmtMoney(k.freight_unit)} foot="R$/un entregue" icon="▮"/><KpiCard label="Entregas no prazo" value={fmtPct(k.on_time)} foot="On Time" state={k.on_time>=.95?'good':'warn'} icon="▥"/><KpiCard label="Custo logístico total" value={fmtMoney(k.logistics_cost)} foot="frete total" icon="▮"/><KpiCard label="Pedidos críticos" value={fmtNumber(k.critical_orders)} foot="não OTIF" state="bad" icon="!"/><KpiCard label="Receita em risco" value={fmtMoney(k.revenue_risk)} foot="exposição; não EBITDA" state="bad" icon="▮"/></div>
 <div className="grid grid-12">
  <Panel className="span-7" title="OTIF e Nível de Serviço" subtitle="OTIF em barras; On Time e In Full em linhas; meta 95%." icon="◎"><ServiceChart data={data.monthly||[]}/></Panel>
  <Panel className="span-5" title="Onde está o dinheiro?" subtitle="Apenas valores suportados pela base são monetizados." tag="SEM ARBITRARIEDADE" icon="▮"><div className="money-list"><Money label="Frete total" value={money.freight_total} foot="custo base, não oportunidade automática"/><Money label="Receita em risco" value={money.revenue_risk} foot="pedidos não OTIF; não EBITDA garantido"/><Money label="Urgências" value={null} foot={`${fmtNumber(money.urgencies)} ocorrências; custo incremental N/D`}/>{(money.unsupported||[]).map((x,i)=><Money key={i} label={x} value={null} foot="dado necessário"/>)}</div></Panel>
  <Panel className="span-5" title="Ofensores do OTIF" subtitle="Pareto de causas, ocorrências e receita em risco." tag="PARETO" icon="!"><DataTable rows={data.causes||[]} columns={[{key:'cause',label:'Causa'},{key:'count',label:'Ocorrências'},{key:'share',label:'% total',render:v=>fmtPct(v)},{key:'revenue_risk',label:'Receita em risco',render:v=>fmtMoney(v)}]}/></Panel>
  <Panel className="span-7" title="Frete por rota / região" subtitle="R$/un, ocupação, urgências e lead time para drill-down." icon="⌖"><DataTable rows={data.routes||[]} columns={[{key:'route',label:'Rota'},{key:'region',label:'Região'},{key:'freight_unit',label:'R$/un',render:v=>fmtMoney(v)},{key:'freight_total',label:'Frete total',render:v=>fmtMoney(v)},{key:'occupancy',label:'Ocupação',render:v=>fmtPct(v)},{key:'urgencies',label:'Urgências'},{key:'lead_time',label:'Lead time',render:v=>`${fmtNumber(v,1)} d`} ]}/></Panel>
  <Panel className="span-7" title="Pedidos críticos" subtitle="Pedido, cliente, transportadora, causa e valor em risco." tag="DRILL-DOWN" icon="▦"><DataTable rows={data.critical||[]} columns={[{key:'order',label:'Pedido'},{key:'client',label:'Cliente'},{key:'region',label:'Região'},{key:'carrier',label:'Transportadora'},{key:'cause',label:'Causa'},{key:'status',label:'Status'},{key:'risk',label:'Valor em risco',render:v=>fmtMoney(v)}]}/></Panel>
  <Panel className="span-5" title="Resumo executivo" subtitle="Quatro leituras executivas priorizadas por impacto." icon="▤"><AnalysisList items={data.insights||[]}/></Panel>
  <Panel className="span-5" title="Conclusão executiva" subtitle="Serviço, custo e exposição traduzidos em decisão." tag="DECISÃO" icon="◎"><ExecutiveConclusion data={data.executive_conclusion}/></Panel>
  <Panel className="span-7" title="Drill-down logístico" subtitle="Causa → pedido/transportadora/rota → valor em risco → Diagnóstico." tag="CAUSA → PEDIDO" icon="⌕"><DrilldownTable items={data.drilldowns||[]}/></Panel>
  <Panel className="span-12" title="Ações recomendadas" subtitle="Ações conectadas a causa, rota/pedido e prazo de gestão." icon="✓"><RecommendationList items={data.recommendations||[]}/></Panel>
 </div></>
}

function Financas({data}){
 const k=data.kpis||{},bridge=data.bridge||{},close=data.closing||{}
 const closingOk=['margin_diff','result_diff','ebitda_diff','bridge_diff'].every(x=>Math.abs(Number(close[x]||0))<1)
 return <><div className="kpi-grid cols-6"><KpiCard label="Receita Líquida" value={fmtMoney(k.revenue)} foot="linha principal" icon="▮"/><KpiCard label="Margem Industrial" value={fmtMoney(k.industrial_margin)} foot="resultado após custos industriais" state="good" icon="▦"/><KpiCard label="EBITDA Gerencial" value={fmtMoney(k.ebitda)} foot={`${fmtPct(k.ebitda_margin)} da receita`} state="good" icon="▮"/><KpiCard label="Custo Variável" value={fmtMoney(k.variable_cost)} foot="MP + MOD + energia" icon="▦"/><KpiCard label="GGF + Frete" value={fmtMoney(k.ggf_freight)} foot="frete permanece em GGF" icon="▦"/><KpiCard label="Despesas Operacionais" value={fmtMoney(k.opex)} foot="OPEX recorrente" icon="▦"/></div>
 <div className="grid grid-12 finance-layout">
  <Panel className="span-7 finance-dre-panel" title="DRE Gerencial" subtitle="Estrutura oficial; Receita Líquida, Margem Industrial, Resultado Industrial e EBITDA Gerencial em destaque." tag={closingOk?'FECHADA':'REVISAR'} icon="▮"><DataTable rows={data.dre||[]} columns={[{key:'line',label:'Linha',render:(v,r)=><span className={r.key?'key-line':''}>{v}</span>},{key:'value',label:'Valor',render:(v,r)=><strong className={r.key?'key-line':''}>{fmtMoney(v)}</strong>} ]}/><div className="closing-strip"><span>Fechamento matemático</span><strong className={closingOk?'good-text':'bad-text'}>{closingOk?'DRE + Bridge reconciliadas':'Diferença encontrada'}</strong></div></Panel>
  <div className="span-5 finance-side-stack">
   <Panel title="Estrutura de custos" subtitle="Composição de MP, MOD, GGF, fixos e OPEX." tag="COMPOSIÇÃO" icon="◎"><div className="chart-sm-wrap"><CostDonut data={data.costs||[]}/></div></Panel>
   <Panel title="Leitura executiva financeira" subtitle="O que mais explica o resultado e onde atuar primeiro." tag="INSIGHTS" icon="◆"><AnalysisList items={(data.insights||[]).slice(0,4)}/></Panel>
  </div>
  <Panel className="span-8" title="Bridge do EBITDA Gerencial" subtitle={`${bridge.current_period||'Anterior'} → ${bridge.projected_period||'Atual'} por drivers reais da DRE.`} tag="RECONCILIAÇÃO EXATA" icon="▦"><BridgeChart current={bridge.current} projected={bridge.projected} items={bridge.items||[]}/><div className="bridge-recon"><div><span>EBITDA anterior</span><strong>{fmtMoney(bridge.current)}</strong></div><div><span>Δ drivers</span><strong>{fmtMoney((bridge.items||[]).reduce((a,x)=>a+(x.impact||0),0))}</strong></div><div><span>EBITDA atual</span><strong>{fmtMoney(bridge.projected)}</strong></div><div><span>Diferença</span><strong className={Math.abs(bridge.reconciliation_diff||0)<1?'good-text':'bad-text'}>{fmtMoney(bridge.reconciliation_diff)}</strong></div></div></Panel>
  <Panel className="span-4" title="Onde está o dinheiro?" subtitle="Pressões e oportunidades originadas na operação." tag="ORIGEM OPERACIONAL" icon="▮"><div className="money-list">{(data.operational_pressures||[]).slice(0,7).map((x,i)=><Money key={i} label={x.problem} value={x.impact} foot={`${x.front} · ${x.evidence||'evidência operacional'}`} link={x.path}/>)}</div><div className="finance-risk-note"><div><span>Receita em risco logística</span><strong>{fmtMoney(data.risk?.logistics_revenue_risk)}</strong><small>exposição comercial; fora do EBITDA</small></div><div><span>Estoque em excesso</span><strong>{fmtMoney(data.risk?.working_capital_excess)}</strong><small>capital de giro; fora do EBITDA</small></div></div></Panel>
  <Panel className="span-8" title="Tendência financeira" subtitle="Receita Líquida, Margem Industrial e EBITDA Gerencial — série real." tag="MENSAL" icon="▦"><FinanceTrend data={data.trend||[]}/></Panel>
  <Panel className="span-4" title="Conclusão executiva" subtitle="Resultado financeiro conectado à origem operacional e à decisão." tag="DECISÃO" icon="▤"><ExecutiveConclusion data={data.executive_conclusion}/><div className="separator"/><div className="finance-priority"><span>Prioridade de gestão</span><b>{data.operational_pressures?.[0]?.problem||'Sem pressão monetizada material'}</b><small>{data.operational_pressures?.[0]?.front||'—'}</small></div></Panel>
  <Panel className="span-7" title="Drill-down operação → DRE" subtitle="Pressão financeira → módulo operacional de origem → evidência." tag="RASTREABILIDADE" icon="⌕"><DrilldownTable items={data.drilldowns||[]}/></Panel>
  <Panel className="span-5" title="Recomendações executivas" subtitle="Atacar a origem operacional antes do efeito financeiro." tag="PRIORIDADE" icon="✓"><RecommendationList items={data.recommendations||[]}/></Panel>
 </div></>
}

function ValidatedCausalTree({model}){
 const root=model?.root||{}, branches=model?.branches||[]
 if(!branches.length)return <div className="data-note">Árvore causal não disponível com evidência suficiente.</div>
 return <div className="validated-causal-tree">
   <div className="causal-root node red"><strong>{root.label||'OEE abaixo da meta'}</strong><span>{fmtPct(root.current)} vs. meta {fmtPct(root.target)}</span><b>{root.gap!=null?`${fmtNumber(Number(root.gap)*100,1)} p.p.`:'—'} · {fmtMoney(root.impact)}</b></div>
   <div className="causal-branch-list">{branches.map((b,i)=><div className="causal-branch" key={b.component||i}><span className="branch-connector">→</span><div className={`node ${i===0?'orange':i===1?'green':'blue'}`}><strong>{b.component}</strong><span>{fmtPct(b.current)} vs. {fmtPct(b.target)}</span><b>{b.gap!=null?`${fmtNumber(Number(b.gap)*100,1)} p.p.`:'—'} · {fmtMoney(b.impact)}</b></div><span className="branch-connector">→</span><div className="node cause-node"><strong>{b.offender||'Dado necessário'}</strong><span>{b.evidence||'Evidência não disponível'}</span></div><div className="evidence-list"><span className="evidence-title">Causa raiz / evidência</span>{(b.evidence_items||[]).slice(0,4).map((e,j)=><div key={j}><i>•</i><span><b>{e.label}</b>{e.evidence&&` — ${e.evidence}`}</span>{e.impact? <em>{fmtMoney(e.impact)}</em>:null}</div>)}</div></div>)}</div>
   <div className="causal-note">{model?.note}</div>
 </div>
}
function QuadrantSummary({matrix}){const c=matrix?.counts||{},v=matrix?.values||{};const names=['Quick Wins','Grandes Projetos','Melhorias Incrementais','Projetos Estruturantes'];return <div className="quadrant-summary">{names.map(n=><div key={n} className={`quadrant-chip ${n==='Quick Wins'?'qw':n==='Grandes Projetos'?'gp':n==='Melhorias Incrementais'?'mi':'pe'}`}><span>{n}</span><b>{fmtNumber(c[n]||0)} ações</b><small>{fmtMoney(v[n]||0)}</small></div>)}</div>}

function Diagnostico({data}){
 const search=useSearchParams(); const focus=search.get('focus'); const front=search.get('front')
 const c=data.cards||{},probs=data.problems||[],priced=data.priced_problems||[],top=probs[0],matrix=data.matrix?.items||priced.map(x=>({name:x.problem,impact:x.impact,effort:x.effort,quadrant:x.quadrant}))
 const focused=probs.find(x=>(focus&&String(x.problem||'').toLowerCase().includes(focus.toLowerCase()))||(front&&x.front===front))
 return <><div className="kpi-grid cols-6"><KpiCard label="Problemas identificados" value={fmtNumber(c.problems)} foot="6 frentes avaliadas" icon="⌕"/><KpiCard label="Impacto financeiro total" value={fmtMoney(c.impact)} foot="impactos diretos únicos" state="bad" icon="!"/><KpiCard label="Potencial de captura" value={fmtMoney(c.potential)} foot="premissa MVP explícita" state="good" icon="↗"/><KpiCard label="Quick-wins" value={fmtMoney(c.quick_value)} foot="até 90 dias" icon="⚡"/><KpiCard label="Ações recomendadas" value={fmtNumber(c.actions)} foot="priorizadas" icon="◎"/><KpiCard label="Payback médio" value={c.payback_months?`${fmtNumber(c.payback_months,1)} meses`:'N/D'} foot="investimento necessário para calcular" icon="▦"/></div>
 { (focus||front) && <Panel title="Drill-down recebido" subtitle="Recorte vindo da tela operacional; aprofunde sem perder o contexto da planta." tag="CONTEXTO" icon="⌕">{focused?<div className="focus-strip"><div><span>Frente</span><strong>{focused.front}</strong></div><div><span>Problema</span><strong>{focused.problem}</strong></div><div><span>Evidência</span><strong>{focused.evidence||'Dado necessário'}</strong></div><div><span>Impacto / risco</span><strong>{focused.impact?fmtMoney(focused.impact):fmtMoney(focused.risk_value)}</strong></div></div>:<div className="data-note">O recorte foi preservado, mas não há correspondência exata no Pareto atual; use a frente abaixo para aprofundar.</div>}</Panel>}
 <div className="grid grid-12">
  <Panel className="span-6" title="Resumo por frente" subtitle="Problemas, impacto direto, risco e potencial de captura." tag="6 FRENTES" icon="▦"><DataTable rows={data.fronts||[]} columns={[{key:'front',label:'Frente'},{key:'problems',label:'Problemas'},{key:'impact',label:'Impacto',render:v=>fmtMoney(v)},{key:'risk',label:'Risco',render:v=>fmtMoney(v)},{key:'potential',label:'Potencial',render:v=>fmtMoney(v)},{key:'capture',label:'% captura',render:v=>v===null?'—':fmtPct(v)}]}/></Panel>
  <Panel className="span-6" title="Árvore de causas" subtitle="KPI → componente → ofensor → causa/evidência → impacto." tag="EVIDÊNCIA" icon="⌘"><ValidatedCausalTree model={data.causal_model}/></Panel>
  <Panel className="span-4" title="Pareto de problemas" subtitle="Impacto financeiro direto por problema." icon="▮"><HorizontalBars data={priced} dataKey="impact" nameKey="problem"/></Panel>
  <Panel className="span-4" title="Matriz Impacto × Esforço" subtitle="Quick Wins, Grandes Projetos, Melhorias Incrementais e Projetos Estruturantes." tag="4 QUADRANTES" icon="◎"><MatrixChart data={matrix} impactSplit={data.matrix?.impact_split} effortSplit={data.matrix?.effort_split||2.5}/><QuadrantSummary matrix={data.matrix}/><div className="matrix-note">Impacto vem do motor; esforço/horizonte classificam a ação. Projetos estruturantes concentram maior esforço e/ou prazo.</div></Panel>
  <Panel className="span-4" title="Quick-wins — até 90 dias" subtitle="Baixo esforço e evidência disponível." icon="⚡"><div className="alert-list">{(data.quickwins||[]).slice(0,6).map((x,i)=><div className="alert" key={i}><span className="alert-dot good-dot">{i+1}</span><div><b>{x.problem}</b><span>{x.evidence}</span></div><strong>{x.impact?fmtMoney(x.impact):`${fmtMoney(x.risk_value)} risco`}</strong></div>)}</div></Panel>
  <Panel className="span-4" title="Ganho por horizonte" subtitle="Até 90 dias, 3–6 meses e 6–12 meses." icon="▦"><div className="horizon-grid">{(data.horizons||[]).map((x,i)=><div className="horizon-card" key={i}><span>{x.horizon}</span><strong>{fmtMoney(x.impact)}</strong><small>{fmtNumber(x.problems)} problemas · risco {fmtMoney(x.risk)}</small></div>)}</div></Panel>
  <Panel className="span-4" title="Principais insights" subtitle="Leituras derivadas dos dados e da árvore causal." icon="◆"><AnalysisList items={data.insights||[]}/></Panel>
  <Panel className="span-4" title="Risco de não agir" subtitle="Impacto direto e risco permanecem separados." icon="!"><div className="metric-trio"><div className="metric-box"><span>Impacto direto</span><strong className="bad">{fmtMoney(data.risk?.direct_impact)}</strong><p>efeito monetizado</p></div><div className="metric-box"><span>Receita/margem em risco</span><strong className="warn">{fmtMoney(data.risk?.revenue_risk)}</strong><p>não é EBITDA garantido</p></div><div className="metric-box"><span>Prioridade</span><strong>{top?'1':'—'}</strong><p>{data.risk?.top_problem||'sem problema material'}</p></div></div></Panel>
  <Panel className="span-5" title="Conclusão executiva" subtitle="Do Pareto à sequência de captura." tag="DECISÃO" icon="▤"><ExecutiveConclusion data={data.executive_conclusion}/></Panel>
  <Panel className="span-7" title="Drill-down para telas de origem" subtitle="Problema → evidência → impacto/risco → módulo operacional responsável." tag="VOLTA À CAUSA" icon="⌕"><DrilldownTable items={data.drilldowns||[]}/></Panel>
  <Panel className="span-12" title="Recomendação executiva" subtitle="Sequência priorizada, evidência, horizonte e valor antes do Plano de Ação." tag="PRIORIDADE" icon="◎"><DataTable rows={data.recommendations||[]} columns={[{key:'rank',label:'#'},{key:'problem',label:'Problema'},{key:'front',label:'Frente'},{key:'action',label:'Ação recomendada'},{key:'horizon',label:'Horizonte'},{key:'impact',label:'Impacto direto',render:v=>fmtMoney(v)},{key:'risk_value',label:'Risco',render:v=>fmtMoney(v)},{key:'path',label:'Drill-down',render:v=>v?<Drill href={v}>Abrir</Drill>:'—'}]}/></Panel>
 </div>{data.assumptions?.map((a,i)=><div className="footer-note" key={i}>Premissa / regra: {a}</div>)}</>
}

function Alavancas({data,plant}){
 const cur=data.current||{},suggestions=data.suggestions||{}; const [targets,setTargets]=useState(cur); const [sim,setSim]=useState(null); const [simErr,setSimErr]=useState('')
 useEffect(()=>{setTargets(cur);setSim(null)},[JSON.stringify(cur)])
 useEffect(()=>{if(!Object.keys(targets).length)return;const t=setTimeout(()=>{setSimErr('');getJSON('/api/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plant,targets})}).then(setSim).catch(e=>setSimErr(String(e)))},220);return()=>clearTimeout(t)},[JSON.stringify(targets),plant])
 const e=sim?.ebitda||{current:data.kpis?.ebitda,projected:data.kpis?.ebitda,delta:0,margin_current:data.kpis?.margin,margin_projected:data.kpis?.margin}
 const leverDefs=[
  ['volume','Volume vendido','un','number'],['price','Preço médio','R$/un','money'],['mix','Mix de produtos','% maior valor','pct'],['mp_price','Preço de MP','R$/kg','money2'],
  ['mp_consumption','Consumo específico MP','kg/un','decimal'],['freight_unit','Frete / unidade','R$/un','money2'],['contracts','Contratos / serviços','R$','money'],['fixed','Custo fixo','R$','money']
 ]
 const currentOee=(cur.availability||0)*(cur.performance||0)*(1-(cur.scrap||0)); const projOee=sim?.oee?.projected??currentOee; const lossNow=cur.material_loss||0; const lossTarget=Math.max((targets.mp_consumption||0)/(data.assumptions?.std_mp_kg_un||targets.mp_consumption||1)-1,0)
 const baseDre=(data.dre||[]).map(r=>({line:r.line,current:r.value,projected:r.value,delta:0,delta_pct:0})); const dreRows=sim?.dre_compare?.length?sim.dre_compare:baseDre
 const bridgeItems=sim?.bridge?.items||[]; const impactMap=Object.fromEntries(bridgeItems.map(x=>[x.key,x.impact])); if(impactMap.freight!==undefined&&impactMap.freight_unit===undefined)impactMap.freight_unit=impactMap.freight
 const keyLines=new Set(['Receita Líquida','Margem Industrial','Resultado Industrial','EBITDA Gerencial','Margem EBITDA'])
 return <><div className="kpi-grid cols-6"><KpiCard label="Receita Líquida Atual" value={fmtMoney(data.kpis?.revenue)} foot="cenário base" icon="▮"/><KpiCard label="EBITDA Gerencial Atual" value={fmtMoney(e.current)} foot="cenário base" icon="▮"/><KpiCard label="Potencial das Alavancas" value={fmtMoney(e.delta)} foot={Math.abs(e.delta||0)<1?'cenário sem alteração':'incremento calculado'} state={(e.delta||0)>=0?'good':'bad'} icon="◎"/><KpiCard label="EBITDA Projetado" value={fmtMoney(e.projected)} foot="cenário simulado" state={(e.delta||0)>=0?'good':'bad'} icon="↗"/><KpiCard label="Margem EBITDA Atual" value={fmtPct(e.margin_current)} foot="base" icon="%"/><KpiCard label="Margem EBITDA Projetada" value={fmtPct(e.margin_projected)} foot="simulada" state={(e.margin_projected||0)>=(e.margin_current||0)?'good':'bad'} icon="%"/></div>
 <div className="grid grid-12 alavancas-layout">
  <Panel className="span-7 lever-panel" title="Principais alavancas editáveis" subtitle="Defina a Meta a partir do Atual e veja o impacto recalculado na DRE e no EBITDA Gerencial." tag="ATUAL → META" icon="◆"><div className="button-row"><button className="control-btn control-primary" onClick={()=>setTargets({...cur,...suggestions})}>Aplicar cenário sugerido</button><button className="control-btn" onClick={()=>setTargets(cur)}>Resetar base</button></div><div className="lever-grid">{leverDefs.map(([key,label,unit,kind])=><Lever key={key} k={key} label={label} unit={unit} kind={kind} current={cur[key]} target={targets[key]} impact={impactMap[key]} setTargets={setTargets}/>)}</div><div className="data-note">Perdas de material são derivadas do consumo específico para evitar dupla contagem. Atual {fmtPct(lossNow)} → Meta derivada {fmtPct(lossTarget)}.</div></Panel>
  <Panel className="span-5 alavanca-dre" title="DRE Atual × Projetado" subtitle="A DRE base já aparece; ao alterar uma Meta, o cenário projetado e os deltas são recalculados." tag="RECONCILIAÇÃO" icon="▮"><DataTable rows={dreRows} columns={[{key:'line',label:'DRE Gerencial',render:v=><span className={keyLines.has(v)?'key-line':''}>{v}</span>},{key:'current',label:'Atual',render:v=>fmtMoney(v)},{key:'projected',label:'Projetado',render:v=><strong>{fmtMoney(v)}</strong>},{key:'delta',label:'Δ R$',render:v=><span className={Number(v)>0?'good-text':Number(v)<0?'bad-text':''}>{fmtMoney(v)}</span>},{key:'delta_pct',label:'Δ %',render:v=>v===null||v===undefined?'—':<span className={Number(v)>0?'good-text':Number(v)<0?'bad-text':''}>{fmtPct(v)}</span>}]}/><div className="closing-strip"><span>EBITDA projetado</span><strong>{fmtMoney(e.projected)}</strong></div></Panel>
  <Panel className="span-8" title="Produção & OEE" subtitle="OEE é resultado; capacidade adicional só vira EBITDA quando houver demanda ou custo evitado." tag="OEE = DISP. × PERF. × QUAL." icon="◉"><div className="oee-driver-grid"><div className="oee-gauge" style={{background:`conic-gradient(var(--cyan) 0 ${Math.max(0,Math.min(100,projOee*100))}%,#183a51 ${Math.max(0,Math.min(100,projOee*100))}% 100%)`}}><strong>{fmtPct(projOee)}</strong><span>OEE projetado</span></div><Driver label="Disponibilidade" k="availability" cur={cur.availability} value={targets.availability} setTargets={setTargets}/><Driver label="Performance" k="performance" cur={cur.performance} value={targets.performance} setTargets={setTargets}/><Driver label="Refugo" k="scrap" cur={cur.scrap} value={targets.scrap} setTargets={setTargets}/></div><div className="bridge-recon"><div><span>OEE atual</span><strong>{fmtPct(sim?.oee?.current??currentOee)}</strong></div><div><span>OEE projetado</span><strong>{fmtPct(projOee)}</strong></div><div><span>Capacidade capturada</span><strong>{fmtNumber(sim?.oee?.captured_units)} un</strong></div><div><span>Volume comercial adicional</span><strong>{fmtNumber(sim?.oee?.commercial_units)} un</strong></div></div></Panel>
  <Panel className="span-4" title="Qualidade / Refugo" subtitle="Refugo é input; Qualidade = 1 − Refugo." tag="DERIVADO" icon="◇"><div className="metric-box"><span>Qualidade projetada</span><strong>{fmtPct(sim?.oee?.quality ?? (1-(targets.scrap??cur.scrap??0)))}</strong><p>Disponibilidade e Performance são drivers causais. O ganho de capacidade é monetizado uma única vez.</p></div>{simErr&&<div className="data-note bad-text">{simErr}</div>}</Panel>
  <Panel className="span-9" title="Bridge de EBITDA Gerencial" subtitle="EBITDA Atual + impactos únicos = EBITDA Projetado." tag="RECONCILIADO" icon="▦"><BridgeChart current={e.current} projected={e.projected} items={bridgeItems}/><div className="bridge-recon"><div><span>EBITDA Atual</span><strong>{fmtMoney(e.current)}</strong></div><div><span>Δ Bridge</span><strong>{fmtMoney(bridgeItems.reduce((a,x)=>a+(x.impact||0),0))}</strong></div><div><span>EBITDA Projetado</span><strong>{fmtMoney(e.projected)}</strong></div><div><span>Diferença</span><strong className={Math.abs(sim?.bridge?.reconciliation_diff||0)<1?'good-text':'bad-text'}>{fmtMoney(sim?.bridge?.reconciliation_diff||0)}</strong></div></div></Panel>
  <Panel className="span-3" title="Composição do incremento" subtitle="Participação das alavancas positivas no Δ EBITDA, não sobre receita total." icon="◎"><CostDonut data={bridgeItems.filter(x=>x.impact>0).map(x=>({name:x.label,value:x.impact}))}/><div className="data-note">Quick-wins e Impacto×Esforço pertencem ao Diagnóstico, não a esta tela.</div></Panel>
  <Panel className="span-4" title="Principais insights do cenário" subtitle="Leituras derivadas do cenário recalculado pelo motor." icon="◆"><AnalysisList items={sim?.insights||[]}/></Panel>
  <Panel className="span-4" title="Conclusão executiva" subtitle="O que o cenário muda no resultado e o que validar antes de executar." tag="DECISÃO" icon="▤"><ExecutiveConclusion data={sim?.executive_conclusion||data.executive_conclusion}/></Panel>
  <Panel className="span-4" title="Recomendações do cenário" subtitle="Validação e estruturação das maiores alavancas." icon="✓"><RecommendationList items={sim?.recommendations||[]}/></Panel>
  <Panel className="span-12" title="Drill-down das alavancas" subtitle="Alavanca → impacto reconciliado → Diagnóstico para validação operacional." tag="BRIDGE → CAUSA" icon="⌕"><DrilldownTable items={sim?.drilldowns||[]}/></Panel>
 </div></>
}
function leverDisplay(v,kind){const n=Number(v);if(!Number.isFinite(n))return '—';if(kind==='pct')return fmtPct(n);if(kind==='money'||kind==='money2')return fmtMoney(n);if(kind==='decimal')return fmtNumber(n,2);return fmtNumber(n,0)}
function leverInput(v,kind){const n=Number(v);if(!Number.isFinite(n))return '';return kind==='pct'?Number((n*100).toFixed(2)):n}
function leverStore(raw,kind){const n=Number(raw);return kind==='pct'?n/100:n}
function Lever({k,label,unit,kind,current,target,impact,setTargets}){return <div className="lever-card"><label><span>{label}</span><small>{unit}</small></label><div className="lever-flow"><div className="lever-current"><span>Atual</span><strong>{leverDisplay(current,kind)}</strong></div><b>→</b><div className="lever-target"><span>Meta</span><input type="number" step={kind==='pct'?'0.1':'any'} value={leverInput(target,kind)} onChange={e=>setTargets(s=>({...s,[k]:leverStore(e.target.value,kind)}))}/></div></div><div className="lever-delta"><span>Variação</span><b>{Number.isFinite(Number(current))&&Number.isFinite(Number(target))?(kind==='pct'?`${fmtNumber((Number(target)-Number(current))*100,1)} p.p.`:fmtNumber(Number(target)-Number(current),kind==='decimal'||kind==='money2'?2:0)):'—'}</b>{impact!==undefined&&<em className={Number(impact)>=0?'good-text':'bad-text'}>{fmtMoney(impact)}</em>}</div></div>}
function Driver({label,k,cur,value,setTargets}){const shown=Number.isFinite(Number(value))?Number((Number(value)*100).toFixed(2)):'';return <div className="driver-card"><b>{label}</b><div className="driver-input-wrap"><input type="number" step="0.1" min="0" max="100" value={shown} onChange={e=>setTargets(s=>({...s,[k]:Number(e.target.value)/100}))}/><span>%</span></div><small>Atual {fmtPct(cur)} → Meta {fmtPct(value)}</small></div>}


function PlanoAcao({data,plant}){
 const storageKey=`ip_action_plan_${plant}`; const [actions,setActions]=useState(data.actions||[])
 useEffect(()=>{try{const saved=window.localStorage.getItem(storageKey);if(saved){const parsed=JSON.parse(saved);if(Array.isArray(parsed))setActions(parsed);else setActions(data.actions||[])}else setActions(data.actions||[])}catch{setActions(data.actions||[])}},[storageKey,JSON.stringify(data.actions||[])])
 useEffect(()=>{try{window.localStorage.setItem(storageKey,JSON.stringify(actions))}catch{}},[storageKey,actions])
 const change=(id,key,value)=>setActions(a=>a.map(x=>x.id===id?{...x,[key]:value}:x)); const add=()=>setActions(a=>[...a,{id:`A${String(a.length+1).padStart(2,'0')}`,priority:a.length+1,front:'Manual',problem:'Nova ação',action:'Descrever ação',horizon:'Até 90 dias',due:'30 dias',owner:'A definir',status:'Planejada',potential:0,risk_value:0,captured:0,source_path:'/diagnostico'}])
 const potential=actions.reduce((a,x)=>a+Number(x.potential||0),0),captured=actions.reduce((a,x)=>a+Number(x.captured||0),0),done=actions.filter(x=>x.status==='Concluída').length
 return <><div className="kpi-grid cols-4"><KpiCard label="Ações no plano" value={fmtNumber(actions.length)} foot={`${done} concluídas`} icon="◇"/><KpiCard label="Valor potencial" value={fmtMoney(potential)} foot="não é captura realizada" icon="▮"/><KpiCard label="Valor capturado" value={fmtMoney(captured)} foot="registrado após evidência" state="good" icon="✓"/><KpiCard label="Captura / potencial" value={potential?fmtPct(captured/potential):'—'} foot="acompanhamento executivo" icon="◎"/></div><Panel title="Plano de Ação" subtitle="Prioridade → responsável → prazo → status → valor capturado." tag="EDITÁVEL" icon="◇"><div className="button-row"><button className="control-btn control-primary" onClick={add}>+ Nova ação</button><Link className="control-btn" href={`/diagnostico?plant=${encodeURIComponent(plant)}`}>Voltar ao Diagnóstico</Link></div><div className="action-table-wrap"><table className="action-table"><thead><tr><th>#</th><th>Ação</th><th>Frente</th><th>Responsável</th><th>Prazo</th><th>Status</th><th>Potencial</th><th>Capturado</th><th>Origem</th></tr></thead><tbody>{actions.map((x,i)=><tr key={x.id||i}><td>{i+1}</td><td><textarea value={x.action||''} onChange={e=>change(x.id,'action',e.target.value)}/></td><td>{x.front}</td><td><input value={x.owner||''} onChange={e=>change(x.id,'owner',e.target.value)}/></td><td><input value={x.due||''} onChange={e=>change(x.id,'due',e.target.value)}/></td><td><select value={x.status||'Planejada'} onChange={e=>change(x.id,'status',e.target.value)}><option>Planejada</option><option>Em andamento</option><option>Bloqueada</option><option>Concluída</option></select></td><td>{fmtMoney(x.potential)}</td><td><input type="number" min="0" value={x.captured??0} onChange={e=>change(x.id,'captured',Number(e.target.value||0))}/></td><td><Drill href={x.source_path}>Abrir</Drill></td></tr>)}</tbody></table></div></Panel><div className="footer-note">O plano é persistido localmente no navegador nesta build. Persistência multiusuário/DB continua como etapa de produto.</div></>
}

function Agente({data,plant}){
 const [question,setQuestion]=useState(''),[history,setHistory]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function ask(q=question){const text=String(q||'').trim();if(!text||busy)return;setBusy(true);setError('');try{const r=await getJSON('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plant,question:text})});setHistory(h=>[...h,{q:text,...r}]);setQuestion('')}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <><Panel title="Agente de Performance" subtitle="Pergunte sobre KPI, causa/evidência, impacto financeiro e ação recomendada." tag="MOTOR ANALÍTICO" icon="✦"><div className="agent-starters">{(data.starter_questions||[]).map((q,i)=><button key={i} className="control-btn" onClick={()=>ask(q)}>{q}</button>)}</div><div className="agent-input"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')ask()}} placeholder="Ex.: Onde está o maior impacto financeiro e o que devo fazer?"/><button className="control-btn control-primary" onClick={()=>ask()} disabled={busy}>{busy?'Analisando…':'Perguntar'}</button></div>{error&&<div className="data-note bad-text">{error}</div>}</Panel><div className="agent-history">{history.length===0?<Panel title="Contexto atual" subtitle="O agente usa a mesma base ativa e o mesmo motor das telas." icon="▤"><ExecutiveConclusion data={data.executive_context}/><AnalysisList items={(data.top_problems||[]).slice(0,3).map(x=>({title:x.problem,text:`${x.front} · ${x.impact?fmtMoney(x.impact):fmtMoney(x.risk_value)} · ${x.evidence||'evidência a confirmar'}`}))}/></Panel>:history.map((h,i)=><Panel key={i} title={h.q} subtitle={`${h.plant} · ${h.mode}`} tag="RESPOSTA" icon="✦"><div className="agent-answer"><p>{h.answer}</p>{h.evidence?.length>0&&<div><strong>Evidências</strong><ul>{h.evidence.map((x,j)=><li key={j}>{x}</li>)}</ul></div>}{h.actions?.length>0&&<div><strong>Ações sugeridas</strong><ol>{h.actions.map((x,j)=><li key={j}>{x}</li>)}</ol></div>}<div className="button-row">{h.paths?.map((x,j)=><Drill key={j} href={`${x}?plant=${encodeURIComponent(plant)}`}>Aprofundar</Drill>)}</div></div></Panel>)}</div></>
}

function Relatorios({data,plant}){
 const [selected,setSelected]=useState(null); const pkg=selected?data.packages?.find(x=>x.id===selected):null; const payload=selected?data.payloads?.[selected]:null
 function download(id){const pack=data.packages?.find(x=>x.id===id),content=data.payloads?.[id];if(!pack||!content)return;const blob=new Blob([JSON.stringify({title:pack.title,plant,generated_at:new Date().toISOString(),source:data.generated_from,data:content},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`industrial-performance-${id}-${plant.replaceAll(' ','-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
 return <><div className="report-grid">{(data.packages||[]).map(x=><article className="report-card" key={x.id}><IconBox>▤</IconBox><h3>{x.title}</h3><p>{x.description}</p><div className="report-sections">{x.sections?.map((s,i)=><span key={i}>{s}</span>)}</div><div className="button-row"><button className="control-btn control-primary" onClick={()=>setSelected(x.id)}>Gerar prévia</button><button className="control-btn" onClick={()=>download(x.id)}>Baixar dados</button></div></article>)}</div>{pkg&&<Panel title={`Prévia — ${pkg.title}`} subtitle={`${plant} · ${data.generated_from}`} tag="GERADO DA BASE ATIVA" icon="▤"><div className="button-row report-actions"><button className="control-btn control-primary" onClick={()=>window.print()}>Imprimir / salvar PDF</button><button className="control-btn" onClick={()=>download(pkg.id)}>Baixar dados JSON</button></div><div className="report-preview"><h2>{pkg.title}</h2><p>Planta: <b>{plant}</b></p><p>Seções: {pkg.sections?.join(' · ')}</p><pre>{JSON.stringify(payload,null,2)}</pre></div></Panel>}</>
}


function CentralDados({data}){
 const [file,setFile]=useState(null),[upload,setUpload]=useState(null),[message,setMessage]=useState('')
 async function doUpload(){if(!file)return;const fd=new FormData();fd.append('file',file);try{const r=await getJSON('/api/data-lake/upload',{method:'POST',body:fd});setUpload(r);setMessage(r.publishable?'Workbook processado e apto para publicação.':'Arquivo recebido no RAW com pendências.')}catch(e){setMessage(String(e))}}
 async function publish(){if(!upload?.path)return;try{const r=await getJSON('/api/data-lake/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:upload.path})});setMessage(`Base publicada no app: ${r.active_base}. Atualize a página para recalcular os dashboards.`)}catch(e){setMessage(String(e))}}
 return <><div className="state-rail"><div className="state-box active"><span>BASE ATIVA</span><strong>{data.active_file}</strong></div><div className="state-box"><span>OBJETOS / ABAS</span><strong>{fmtNumber(data.sheets)}</strong></div><div className="state-box"><span>REGISTROS PROCESSADOS</span><strong>{fmtNumber(data.rows)}</strong></div></div><Panel title="Pipeline do Data Lake" subtitle="RAW → classificação → DE/PARA → Standard Model → Data Quality → Semantic/Gold → motores." tag="SEM DEFAULT SILENCIOSO" icon="▣"><div className="pipeline">{data.pipeline?.map((x,i)=><div className="pipe-step" key={i}>{i+1}. {x}</div>)}</div></Panel><div className="grid grid-12"><Panel className="span-5" title="Data Lake & Uploads" subtitle="Receba no RAW, processe e publique somente quando validado." icon="▣"><div className="upload-box"><input type="file" accept=".xlsx,.xls" onChange={e=>setFile(e.target.files?.[0])}/><button className="control-btn control-primary" onClick={doUpload} style={{marginTop:10}}>Processar no Data Lake</button>{upload?.publishable&&<button className="control-btn" onClick={publish} style={{marginTop:8}}>Publicar workbook no App</button>}{message&&<p className="executive-copy">{message}</p>}</div></Panel><Panel className="span-7" title="Qualidade da Carga" subtitle="O que foi aceito e o que precisa de ação." icon="✓"><DataTable rows={(upload?.quality||data.quality||[]).slice(0,18)} columns={[{key:'sheet',label:'Objeto'},{key:'rows',label:'Linhas',render:v=>fmtNumber(v)},{key:'columns',label:'Colunas',render:v=>fmtNumber(v)},{key:'missing_cells',label:'Células faltantes',render:v=>fmtNumber(v)},{key:'status',label:'Status',render:v=>v?<StatusBadge state={v==='ok'?'good':'warn'}>{v}</StatusBadge>:'—'}]}/>{upload&&<div className="total-strip"><span>Estado de interpretação</span><strong>{upload.state}</strong></div>}</Panel></div><Panel title="Falhas / Não Capturado" subtitle="Itens incompletos impedem publicação silenciosa." icon="!">{upload?.missing_required_sheets?.length?<div className="alert-list">{upload.missing_required_sheets.map((x,i)=><div className="alert" key={i}><span className="alert-dot">!</span><div><b>Objeto obrigatório não reconhecido</b><span>{x}</span></div><StatusBadge state="bad">Ação manual</StatusBadge></div>)}</div>:<div className="executive-copy">Nenhuma pendência obrigatória identificada no workbook ativo/processado.</div>}</Panel></>
}

function Money({label,value,foot,link}){return <div className="money-row"><div><span>{label}</span>{foot&&<small>{foot}</small>}</div><strong>{value===null||value===undefined?'N/D':fmtMoney(value)}</strong>{link&&<Drill href={link}>Abrir</Drill>}</div>}
