'use client'
import {useMemo,useState} from 'react'
import {useRouter} from 'next/navigation'
import {KpiCard,Panel,DataTable,StatusBadge,fmtMoney,fmtNumber,fmtPct} from './UI'
import {OeePlantChart,SimpleBars,OeeTrend,ForecastChart,CapacityChart,ServiceChart,CostDonut,BridgeChart,HorizontalBars} from './Charts'
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend,BarChart,Bar,ReferenceLine} from 'recharts'

const colors=['#2d8cff','#27cfaa','#ffc15c','#9d7cff','#ff8272','#50c9ec']
const columns=(pairs)=>pairs.map(([key,label,render])=>({key,label,render}))
const money=v=>fmtMoney(v)
const number=v=>fmtNumber(v)
const pct=v=>fmtPct(v)
const moneyColumns=(field='impact')=>columns([['name','Indicador'],[field,'Valor',money]])
const note=(text)=> <p className="source-note">{text}</p>

export function EvidencePanel({data,onDrill,screen}){
 const insights=data.insights||[];const recs=data.recommendations||[]
 return <div className="grid grid-12">
  <Panel className="span-7" title="Conclusões executivas e evidências" subtitle="Leituras calculadas; observação ≠ causa confirmada ≠ economia capturada." tag="BASE ATIVA" icon="◆">
   {insights.length?<div className="analysis-list">{insights.map((x,i)=><div className="analysis-card" key={i}><strong>{i+1}. {x.title}</strong><span>{x.text}</span><small>Fonte: {x.source||'base ativa'} · {x.kind||'observação'}</small></div>)}</div>:<p className="data-note">A base não permite uma conclusão rastreável adicional para o filtro selecionado.</p>}
  </Panel>
  <Panel className="span-5" title="Recomendações condicionadas" subtitle="Validar causa, impacto e responsável antes de executar." tag="AÇÃO / EVIDÊNCIA" icon="✓">
   {recs.length?<div className="analysis-list">{recs.map((r,i)=><div className="analysis-card" key={i}><strong>{r.title}</strong><span>{r.text}</span><small>Fonte: {r.source||'a confirmar'}</small></div>)}</div>:<p className="data-note">Recomendação não derivável. Abra os ofensores e complete evidências antes de criar um plano.</p>}
   <button className="control-btn drill-btn" onClick={()=>onDrill('','')}>Abrir linhas da fonte ↗</button>
  </Panel>
 </div>
}

function RowTable({rows,cols,onDrill,dimension,valueKey}){
 return <DataTable rows={rows||[]} columns={cols} onRowClick={r=>onDrill(dimension,valueKey?String(r[valueKey]??''):'')} />
}

function MultiTrend({rows=[]}){
 const plants=[...new Set(rows.map(r=>r.plant))];const periods=[...new Set(rows.map(r=>r.period))];const matrix=periods.map(period=>({period,...Object.fromEntries(rows.filter(r=>r.period===period).map(r=>[r.plant,r.oee]))}))
 return <div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={matrix}><CartesianGrid stroke="#17364b" vertical={false}/><XAxis dataKey="period" tick={{fill:'#9bb0bf',fontSize:10}}/><YAxis domain={[0,1]} tickFormatter={v=>`${Math.round(v*100)}%`} tick={{fill:'#9bb0bf',fontSize:10}}/><Tooltip formatter={v=>fmtPct(v)}/><Legend/><ReferenceLine y={.85} stroke="#29d7ef" strokeDasharray="4 4"/>{plants.map((plant,i)=><Line key={plant} dataKey={plant} stroke={colors[i%colors.length]} dot={false} strokeWidth={2}/>)}</LineChart></ResponsiveContainer></div>
}

export function Multiplantas({data,plant,onDrill,onPlant}){
 const c=data.cards||{},rows=data.plants||[],router=useRouter()
 function select(p){onPlant(p);router.push('/cockpit')}
 return <>
 <div className="kpi-grid cols-6"><KpiCard label="Plantas monitoradas" value={fmtNumber(c.plants)} foot="comparação individual"/><KpiCard label="Menor OEE — planta" value={c.worst?.plant||'—'} foot={fmtPct(c.worst?.oee)} state="bad"/><KpiCard label="Maior OEE — planta" value={c.best?.plant||'—'} foot={fmtPct(c.best?.oee)} state="good"/><KpiCard label="Produção do grupo" value={fmtNumber(c.production)} foot="somatória de unidades"/><KpiCard label="Receita Líquida Grupo" value={money(c.revenue)} foot="soma de DREs"/><KpiCard label="EBITDA Gerencial Grupo" value={money(c.ebitda)} foot="soma de DREs"/></div>
 <div className="notice">OEE consolidado do grupo não é calculado: sem método de ponderação aprovado. Todos os OEEs abaixo são por planta.</div>
 <div className="grid grid-12">
  <Panel className="span-6" title="OEE por planta" subtitle="OEE, Disponibilidade, Performance e Qualidade por unidade fabril" icon="▥"><OeePlantChart data={rows}/></Panel>
  <Panel className="span-3" title="Produção por planta" subtitle="Volume realizado no período" icon="▦"><SimpleBars data={rows}/></Panel>
  <Panel className="span-3" title="Custo de conversão por planta" subtitle="R$/un; definição uniforme no motor" icon="▮"><SimpleBars data={rows} valueKey="conversion_cost" color="#32d19a"/></Panel>
  <Panel className="span-8" title="Indicadores por planta" subtitle="Clique na planta para alterar o seletor global e abrir o Cockpit." tag="DRILL-THROUGH" icon="▣"><DataTable rows={rows} onRowClick={r=>select(r.plant)} columns={columns([['plant','Planta'],['production','Produção',number],['oee','OEE',pct],['availability','Disponib.',pct],['performance','Performance',pct],['quality','Qualidade',pct],['conversion_cost','Conversão',money]])}/></Panel>
  <Panel className="span-4" title="Mapa das plantas" subtitle="Sem coordenadas verificadas no cadastro" icon="◇"><div className="notice">Mapa indisponível: o cadastro atual possui região, mas não localização geográfica das plantas. Não serão inventados marcadores.</div><button className="control-btn drill-btn" onClick={()=>onDrill('','')}>Ver cadastro geográfico ↗</button></Panel>
  <Panel className="span-8" title="Evolução de OEE por planta" subtitle="Cada série é apurada por planta e competência" icon="▦"><MultiTrend rows={data.evolution}/></Panel>
  <Panel className="span-4" title="Drill-through operacional" subtitle="Selecione uma planta abaixo para abrir o Cockpit." icon="◎"><div className="analysis-list">{rows.map(r=><button key={r.plant} className="drill-row" onClick={()=>select(r.plant)}>{r.plant}<strong>{pct(r.oee)} →</strong></button>)}</div></Panel>
 </div><EvidencePanel data={data} onDrill={onDrill} screen="multiplantas"/>
 </>
}

export function PCP({data,onDrill}){
 const m=data.metrics||{},off=data.offenders||[],[family,setFamily]=useState('Todas')
 const families=[...new Set((data.family_month||[]).map(x=>x.family))]
 const weeks=(data.family_week||[]).filter(x=>family==='Todas'||x.family===family)
 return <>
 <div className="kpi-grid cols-4"><KpiCard label="Forecast" value={number(m.forecast)} foot="fonte PCP"/><KpiCard label="MRP / Plano" value={number(m.plan)} foot="plano aprovado na base"/><KpiCard label="Produzido" value={number(m.produced)} foot="realizado"/><KpiCard label="Aderência (Produzido/Plano)" value={pct(m.adherence)} foot="execução do planejamento"/></div>
 <div className="grid grid-12">
  <Panel className="span-12" title="Qualidade do Forecast" subtitle="Três métricas complementares calculadas no mesmo universo de SKUs" icon="◎"><div className="metric-trio"><div className="metric-box"><span>MAPE — média dos erros por item</span><strong>{pct(m.mape)}</strong><p>Exclui realizado zero. Forecast=0 e Real&gt;0 gera erro 100%.</p></div><div className="metric-box"><span>WAPE — erro absoluto ponderado</span><strong>{pct(m.wape)}</strong><p>Σ|Real−Forecast| / Σ|Real|. Soma realizado zero → N/A.</p></div><div className="metric-box"><span>Bias — viés de previsão</span><strong>{pct(m.bias)}</strong><p>Σ(Forecast−Real) / Σ|Real|. Positivo = sobreprevisão.</p></div></div></Panel>
  <Panel className="span-7" title="Forecast × Plano × Produzido" subtitle="Identifique gap de planejamento e de execução por mês" icon="▦"><ForecastChart data={data.monthly||[]}/></Panel>
  <Panel className="span-5" title="Família × Semana — erro ponderado" subtitle="Seleção local de família" tag="DRILL LOCAL" icon="▦"><label className="inline-filter">Família <select value={family} onChange={e=>setFamily(e.target.value)}><option>Todas</option>{families.map(x=><option key={x}>{x}</option>)}</select></label><RowTable rows={weeks.slice(0,50)} dimension="Familia" valueKey="family" onDrill={onDrill} cols={columns([['family','Família'],['week','Semana'],['wape','WAPE',pct]])}/></Panel>
  <Panel className="span-6" title="Família × Mês" subtitle="MAPE/WAPE/Bias e série por família" icon="▣"><RowTable rows={(data.family_month||[]).filter(x=>family==='Todas'||x.family===family).slice(0,35)} dimension="Familia" valueKey="family" onDrill={onDrill} cols={columns([['family','Família'],['period','Mês'],['mape','MAPE',pct],['wape','WAPE',pct],['bias','Bias',pct]])}/></Panel>
  <Panel className="span-6" title="Planta × Mês" subtitle="Comparação de erros apurados por planta" icon="▣"><RowTable rows={(data.plant_month||[]).slice(0,36)} dimension="Fabrica" valueKey="plant" onDrill={onDrill} cols={columns([['plant','Planta'],['period','Mês'],['mape','MAPE',pct],['wape','WAPE',pct],['bias','Bias',pct]])}/></Panel>
  <Panel className="span-8" title="Ofensores SKU" subtitle="Contribuição em pontos percentuais ao WAPE, sem confundir com WAPE próprio do SKU" tag="CLIQUE E APROFUNDE" icon="!" ><RowTable rows={off} dimension="SKU" valueKey="sku" onDrill={onDrill} cols={columns([['sku','SKU'],['family','Família'],['wape_contribution','Contrib. WAPE (p.p.)',pct],['bias','Bias',pct],['volume','Realizado',number]])}/></Panel>
  <Panel className="span-4" title="Onde está o dinheiro?" subtitle="Gap não é lucro automaticamente" icon="▮"><div className="metric-box"><span>Gap Plano × Produzido</span><strong>{number(Math.max((m.plan||0)-(m.produced||0),0))} un</strong><p>Valorização depende da demanda vendável e margem incremental. Sem esses vínculos, impacto EBITDA fica N/A.</p></div>{note('Sem atribuição dupla de perdas de PCP e Capacidade.')}</Panel>
 </div><EvidencePanel data={data} onDrill={onDrill} screen="pcp"/>
 </>
}

export function OEE({data,onDrill}){
 const k=data.kpis||{}, eq=data.equipment||[]
 return <>
 <div className="kpi-grid cols-6"><KpiCard label="OEE" value={pct(k.oee)} foot="Disp. × Performance × Qualidade"/><KpiCard label="Disponibilidade" value={pct(k.availability)} foot="tempo produtivo / disponível"/><KpiCard label="Performance" value={pct(k.performance)} foot="termo oficial do OEE"/><KpiCard label="Qualidade" value={pct(k.quality)} foot="aprovado / produzido"/><KpiCard label="Produção Real" value={number(k.production)} foot="unidades"/><KpiCard label="Custos observados" value={money(k.impact)} foot="não são economia integral evitável"/></div>
 <div className="grid grid-12">
  <Panel className="span-8" title="OEE em barras + D/P/Q em linhas" subtitle="Evolução real calculada por competência" icon="▦"><OeeTrend data={data.trend||[]}/></Panel>
  <Panel className="span-4" title="Perdas por equipamentos — Top 10" subtitle="Horas de parada registradas; clique para abrir evento" icon="!"><RowTable rows={eq} dimension="Maquina" valueKey="equipment" onDrill={onDrill} cols={columns([['equipment','Equipamento'],['hours','Horas',v=>fmtNumber(v,1)],['cause','Causa registrada']])}/></Panel>
  <Panel className="span-4" title="Ofensores de Disponibilidade" subtitle="Tempo parado por causa registrada" icon="⌕"><RowTable rows={data.availability_offenders||[]} dimension="Causa" valueKey="cause" onDrill={onDrill} cols={columns([['cause','Causa'],['hours','Horas',v=>fmtNumber(v,1)],['share','Participação',pct]])}/></Panel>
  <Panel className="span-4" title="Ofensores de Performance" subtitle="Velocidade nominal × real; magnitude estimada" icon="◎"><RowTable rows={data.performance_offenders||[]} dimension="Linha" valueKey="line" onDrill={onDrill} cols={columns([['cause','Linha / desvio'],['units','Unidades técnicas',number]])}/>{note('Potencial técnico estimado = realizado × (velocidade nominal / velocidade real − 1), quando velocidades positivas. Não implica demanda nem EBITDA.')}</Panel>
  <Panel className="span-4" title="Ofensores de Qualidade" subtitle="Refugo e retrabalho sem duplicar despesas de MP" icon="◇"><RowTable rows={data.quality_offenders||[]} dimension="Produto" valueKey="product" onDrill={onDrill} cols={columns([['cause','Produto / desvio'],['scrap','Refugo',number],['rework','Retrabalho',number]])}/></Panel>
  <Panel className="span-8" title="OEE por linha" subtitle="Componentes por linha; clique para aprofundar no cadastro de produção" icon="▣"><RowTable rows={data.lines||[]} dimension="Linha" valueKey="line" onDrill={onDrill} cols={columns([['line','Linha'],['oee','OEE',pct],['availability','Disp.',pct],['performance','Performance',pct],['quality','Qualidade',pct]])}/></Panel>
  <Panel className="span-4" title="Onde está o dinheiro?" subtitle="Sem dupla contagem do OEE e seus componentes" icon="▮"><div className="metric-box"><span>Custos observados no período</span><strong>{money(k.impact)}</strong><p>Manutenção e parcela estimada de MP do refugo. Não representam automaticamente despesas evitáveis nem EBITDA capturável.</p></div>{note('Para atribuir margem de volume perdido é necessária demanda vendável confirmada.')}</Panel>
 </div><EvidencePanel data={data} onDrill={onDrill} screen="oee"/>
 </>
}

export function Capacidade({data,onDrill}){
 const k=data.kpis||{},m=data.money||{}
 return <>
 <div className="kpi-grid cols-5"><KpiCard label="Capacidade nominal" value={number(k.capacity)} foot="cadastro do recurso"/><KpiCard label="Produção real" value={number(k.production)} foot="unidades"/><KpiCard label="Utilização" value={pct(k.utilization)} foot="produzido / nominal"/><KpiCard label="Capacidade ociosa" value={number(k.idle)} foot="sem conversão automática em economia"/><KpiCard label="Potencial a 80%" value={number(k.potential)} foot="cenário técnico, não financeiro"/></div>
 <div className="grid grid-12"><Panel className="span-8" title="Capacidade, produção e utilização" subtitle="Dados reais por competência" icon="▦"><CapacityChart data={data.monthly||[]}/></Panel><Panel className="span-4" title="Utilização por linha/recurso" subtitle="Gargalo depende de evidência de restrição no fluxo" icon="▣"><RowTable rows={data.resources||[]} dimension="Linha" valueKey="line" onDrill={onDrill} cols={columns([['line','Linha'],['utilization','Utilização',pct],['capacity','Nominal',number],['status','Status']])}/></Panel>
 <Panel className="span-6" title="Cenários de utilização" subtitle="Atual, 75%, 80%, 85% e 90%; ganho técnico" icon="◎"><DataTable rows={data.scenarios||[]} columns={columns([['utilization','Utilização',pct],['production','Produção cenário',number],['gain','Ganho vs. atual',number]])}/></Panel><Panel className="span-6" title="Onde está o dinheiro?" subtitle="Demanda confirmada é condição obrigatória; custo fixo total não cai automaticamente" icon="▮"><div className="metric-trio"><div className="metric-box"><span>Ociosa</span><strong>{number(m.idle)}</strong></div><div className="metric-box"><span>Recuperável</span><strong>{number(m.recoverable)}</strong></div><div className="metric-box"><span>Monetizável na base</span><strong>{number(m.monetizable)}</strong></div></div><div className="notice">Impacto EBITDA: N/A. {m.impact_status||'Margem incremental por SKU pendente de validação.'}</div></Panel>
 <Panel className="span-6" title="Perdas de capacidade e gargalos" subtitle="Abertura nos registros de recurso; não atribuir causa que não foi capturada" icon="!"><RowTable rows={data.resources||[]} dimension="Linha" valueKey="line" onDrill={onDrill} cols={columns([['line','Linha'],['utilization','Utilização',pct],['status','Status']])}/></Panel><Panel className="span-6" title="Utilização por turno" subtitle="Granularidade condicional" icon="◇"><div className="notice">Granularidade por turno indisponível na aba Capacidade da base ativa. Nenhum turno foi inventado.</div><button className="control-btn drill-btn" onClick={()=>onDrill('','')}>Abrir registros de capacidade ↗</button></Panel></div><EvidencePanel data={data} onDrill={onDrill} screen="capacidade"/>
 </>
}

export function Materiais({data,onDrill}){
 const k=data.kpis||{},moneyData=data.money||{},mat=data.materials||[],supply=data.supply||[]
 const [selected,setSelected]=useState('Todos');const filtered=selected==='Todos'?mat:mat.filter(x=>x.family===selected)
 return <><div className="kpi-grid cols-6"><KpiCard label="Consumo padrão" value={`${fmtNumber(k.standard_unit,2)} kg/un`} foot="base de consumo"/><KpiCard label="Consumo real" value={`${fmtNumber(k.actual_unit,2)} kg/un`} foot="consumo / produção"/><KpiCard label="Desvio de MP" value={money(k.deviation_value)} foot="excesso valorizado; bruto"/><KpiCard label="Cobertura média" value={`${number(k.coverage)} dias`} foot="ver detalhe por material"/><KpiCard label="Materiais críticos" value={number(k.critical)} foot="risco registrado"/><KpiCard label="Aderência fornecedores" value={pct(k.supplier_adherence)} foot="referência do fornecedor"/></div>
 <section className="section-title"><h2>Materiais</h2><span>Consumo, desvios e ofensores por material</span></section><div className="grid grid-12"><Panel className="span-6" title="Consumo padrão × real" subtitle="Valores mensais da base ativa" icon="▦"><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.monthly||[]}><CartesianGrid stroke="#17364b" vertical={false}/><XAxis dataKey="period" tick={{fill:'#8ea5b6',fontSize:10}}/><YAxis tick={{fill:'#8ea5b6',fontSize:10}}/><Tooltip/><Legend/><Bar dataKey="standard" name="Padrão (kg)" fill="#7289a1"/><Bar dataKey="actual" name="Real (kg)" fill="#2d8cff"/></BarChart></ResponsiveContainer></div></Panel><Panel className="span-6" title="R$ perdido por material" subtitle="Desvio positivo × preço da MP da origem" icon="▮"><HorizontalBars data={filtered.slice(0,8)} nameKey="material" dataKey="impact"/></Panel>
 <Panel className="span-8" title="Ofensores de Materiais" subtitle="Clique em material para ver os registros de consumo e a evidência" icon="⌕"><label className="inline-filter">Família <select value={selected} onChange={e=>setSelected(e.target.value)}><option>Todos</option>{[...new Set(mat.map(x=>x.family))].map(x=><option key={x}>{x}</option>)}</select></label><RowTable rows={filtered} dimension="Material" valueKey="material" onDrill={onDrill} cols={columns([['material','Material'],['family','Família'],['deviation','Desvio',pct],['impact','Impacto bruto',money],['evidence','Evidência registrada']])}/></Panel><Panel className="span-4" title="Onde está o dinheiro — Materiais" subtitle="Exposição bruta; refugo potencialmente incluído" icon="▮"><div className="metric-box"><span>Desvio de consumo</span><strong>{money(k.deviation_value)}</strong><p>Não somar novamente refugo/retrabalho sem vinculação que prove não sobreposição.</p></div></Panel></div>
 <section className="section-title"><h2>Supply</h2><span>Continuidade, cobertura e riscos evidenciados</span></section><div className="grid grid-12"><Panel className="span-6" title="Cobertura versus lead time" subtitle="Clique no material para ver cobertura, fornecedor e risco" icon="▣"><RowTable rows={supply} dimension="Material" valueKey="material" onDrill={onDrill} cols={columns([['material','Material'],['coverage','Cobertura (dias)',number],['lead_time','Lead (dias)',number],['risk','Risco']])}/></Panel><Panel className="span-6" title="Fornecedores e aderência" subtitle="Status originado em Supply" icon="◎"><RowTable rows={supply} dimension="Material" valueKey="material" onDrill={onDrill} cols={columns([['supplier','Fornecedor'],['material','Material'],['lead_time','Lead time',number],['adherence','Aderência',pct]])}/></Panel><Panel className="span-8" title="Riscos de abastecimento" subtitle="Impacto de produção não é EBITDA garantido" icon="!"><RowTable rows={supply.filter(x=>x.risk==='Alto'||x.coverage<x.lead_time)} dimension="Material" valueKey="material" onDrill={onDrill} cols={columns([['material','Material'],['supplier','Fornecedor'],['risk','Risco'],['coverage','Cobertura',number],['impact_production','Produção em risco (un)',number]])}/></Panel><Panel className="span-4" title="Onde está o dinheiro — Supply" subtitle="Classes distintas: custo, receita em risco, capital" icon="▮"><div className="money-list"><div className="money-row"><span>Compras emergenciais</span><strong>{money(moneyData.emergency)}</strong></div><div className="money-row"><span>Estoque em excesso (capital)</span><strong>{money(moneyData.excess)}</strong></div><div className="money-row"><span>Produção em risco (un)</span><strong>{number(moneyData.production_risk_units)}</strong></div></div>{note('Estoque/capital fora do EBITDA. Produção em risco não equivale a faturamento perdido.')}</Panel></div><EvidencePanel data={data} onDrill={onDrill} screen="materiais"/></>
}

export function Logistica({data,onDrill}){
 const k=data.kpis||{},[region,setRegion]=useState('Todas'),routes=data.routes||[]
 const shown=region==='Todas'?routes:routes.filter(x=>x.region===region)
 return <><div className="kpi-grid cols-6"><KpiCard label="OTIF" value={pct(k.otif)} foot="meta de referência 95%"/><KpiCard label="Frete / unidade" value={money(k.freight_unit)} foot="GGF / un entregue"/><KpiCard label="Entregas no prazo" value={pct(k.on_time)} foot="On Time"/><KpiCard label="Custo logístico total" value={money(k.logistics_cost)} foot="frete apurado"/><KpiCard label="Pedidos críticos" value={number(k.critical_orders)} foot="total do período"/><KpiCard label="Receita em risco" value={money(k.revenue_risk)} foot="não é EBITDA"/></div><div className="grid grid-12">
 <Panel className="span-7" title="OTIF e nível de serviço" subtitle="OTIF barras; On Time e In Full linhas" icon="▦"><ServiceChart data={data.monthly||[]}/></Panel><Panel className="span-5" title="Onde está o dinheiro?" subtitle="Custos de logística versus receita em risco" icon="▮"><div className="metric-trio"><div className="metric-box"><span>Frete observado</span><strong>{money(k.logistics_cost)}</strong></div><div className="metric-box"><span>Receita em risco</span><strong>{money(k.revenue_risk)}</strong></div><div className="metric-box"><span>OTIF</span><strong>{pct(k.otif)}</strong></div></div>{note('Custos de devolução, reentrega ou frete emergencial: sem segregação monetária suficiente na base; não são inventados.')}</Panel>
 <Panel className="span-5" title="Pareto — ofensores do OTIF" subtitle="Causa registrada e quantidade de pedidos" icon="!"><RowTable rows={data.causes||[]} dimension="Causa_Nao_OTIF" valueKey="cause" onDrill={onDrill} cols={columns([['cause','Causa'],['count','Pedidos',number],['share','Participação',pct]])}/></Panel><Panel className="span-7" title="Frete por rota / região" subtitle="Comparação real R$/un" icon="⌕"><label className="inline-filter">Região <select value={region} onChange={e=>setRegion(e.target.value)}><option>Todas</option>{[...new Set(routes.map(x=>x.region))].map(x=><option key={x}>{x}</option>)}</select></label><RowTable rows={shown} dimension="Rota" valueKey="route" onDrill={onDrill} cols={columns([['route','Rota'],['region','Região'],['freight_unit','R$/un',money]])}/>{note('Mapa regional não exibido: ausência de geometria precisa de rotas no cadastro; tabela preserva comparação verificável.')}</Panel>
 <Panel className="span-12" title="Pedidos críticos — drill-down" subtitle="Clique no pedido para abrir os registros originais, cliente e valor em risco" icon="▣"><RowTable rows={data.critical||[]} dimension="Pedido" valueKey="Pedido" onDrill={onDrill} cols={columns([['Pedido','Pedido'],['Cliente','Cliente'],['Regiao','Região'],['Transportadora','Transportadora'],['Status_OTIF','Status'],['Receita_em_Risco_R$','Receita em risco',money]])}/></Panel></div><EvidencePanel data={data} onDrill={onDrill} screen="logistica"/></>
}

export function Financas({data,onDrill}){
 const k=data.kpis||{},b=data.bridge,recon=data.reconciliation||{},trend=data.monthly||[]
 const keyRows=new Set(['Receita Líquida','Margem Industrial','Resultado Industrial','EBITDA Gerencial'])
 return <><div className="kpi-grid cols-6"><KpiCard label="Receita Líquida" value={money(k.revenue)} foot="DRE Gerencial"/><KpiCard label="Margem Industrial" value={money(k.industrial_margin)} foot="resultado da indústria"/><KpiCard label="EBITDA Gerencial" value={money(k.ebitda)} foot={`${pct(k.ebitda_margin)} sobre receita`}/><KpiCard label="Custo variável" value={money(k.variable_cost)} foot="MP + MOD + energia; A VALIDAR"/><KpiCard label="GGF (inclui frete)" value={money(k.ggf_freight)} foot="classificação oficial"/><KpiCard label="Despesas operacionais" value={money(k.opex)} foot="OPEX corrente"/></div>
 <div className="notice">Fechamento da DRE: diferença máxima {money(recon.max_abs)}. Bridge entre competências é reconciliação contábil, não afirma automaticamente causas operacionais.</div>
 <div className="grid grid-12"><Panel className="span-7" title="DRE Gerencial oficial" subtitle="Receita → Margem Industrial → Resultado Industrial → EBITDA" tag={Math.abs(recon.max_abs||0)<.01?'FECHADA':'VERIFICAR'} icon="▣"><DataTable rows={data.dre||[]} onRowClick={r=>onDrill('','')} columns={[{key:'line',label:'Linha da DRE',render:(v)=>keyRows.has(v)?<strong className="dre-key">{v}</strong>:v},{key:'value',label:'Valor',render:money}]}/></Panel><Panel className="span-5" title="Estrutura de custos" subtitle="MP, MOD, GGF, fixos e OPEX" icon="◎"><CostDonut data={data.costs||[]}/></Panel>
 <Panel className="span-8" title="Bridge EBITDA Gerencial — competências" subtitle={b?`${b.period_current} → ${b.period_projected} | Σ impactos = Δ EBITDA`:'Selecione ao menos duas competências'} tag={b&&Math.abs(b.reconciliation_diff)<.01?'RECONCILIADA':'N/A'} icon="▦">{b?<><BridgeChart current={b.current} projected={b.projected} items={b.items}/><div className="bridge-recon"><div><span>EBITDA anterior</span><strong>{money(b.current)}</strong></div><div><span>Σ variações</span><strong>{money(b.items.reduce((a,x)=>a+x.impact,0))}</strong></div><div><span>EBITDA atual</span><strong>{money(b.projected)}</strong></div><div><span>Diferença</span><strong>{money(b.reconciliation_diff)}</strong></div></div></>:<p>Bridge indisponível para apenas uma competência.</p>}</Panel><Panel className="span-4" title="Onde está o dinheiro?" subtitle="Contas com maior valor observado, sem causalidade presumida" icon="▮"><RowTable rows={(data.cost_drivers||[]).slice(0,9)} dimension="" valueKey="name" onDrill={(d,v)=>onDrill('','')} cols={columns([['name','Conta'],['value','Valor',money]])}/></Panel>
 <Panel className="span-7" title="Tendência financeira" subtitle="Histórico real; Receita Líquida, Margem Industrial e EBITDA" icon="▦"><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><CartesianGrid stroke="#17364b" vertical={false}/><XAxis dataKey="period" tick={{fill:'#8ea5b6',fontSize:10}}/><YAxis tickFormatter={v=>`${(v/1e6).toFixed(0)}mi`} tick={{fill:'#8ea5b6',fontSize:10}}/><Tooltip formatter={money}/><Legend/><Line dataKey="revenue" name="Receita Líquida" stroke="#2d8cff" dot={false}/><Line dataKey="margin" name="Margem Industrial" stroke="#32d19a" dot={false}/><Line dataKey="ebitda" name="EBITDA Gerencial" stroke="#f2bb4f" dot={false}/></LineChart></ResponsiveContainer></div></Panel><Panel className="span-5" title="Contas que explicam a variação" subtitle="Abertura matemática das linhas da ponte, não inferência causal" icon="⌕"><RowTable rows={b?.items||[]} dimension="" valueKey="key" onDrill={(d,v)=>onDrill('','')} cols={columns([['label','Conta'],['impact','Δ período',money]])}/>{note('Frete classificado em GGF; estoque, DPO e DSO ficam fora do EBITDA.')}</Panel></div><EvidencePanel data={data} onDrill={onDrill} screen="financas"/></>
}

export function CentralDados({data,onDrill}){
 const q=data.quality||[]
 return <><div className="notice critical">Data Lake DEMO SOMENTE LEITURA. Base ativa no pacote: {data.active_file||data.source_base}. Publicação de bases e persistência ainda dependem de storage privado, autenticação e validação. Não confundir upload com publicação.</div>
 <div className="kpi-grid cols-4"><KpiCard label="Base ativa" value={data.active_file||'—'} foot="arquivo que alimenta os motores"/><KpiCard label="Tabelas lidas" value={number(data.sheets)} foot="objetos do workbook"/><KpiCard label="Linhas processadas" value={number(data.rows)} foot="linhas lidas do arquivo"/><KpiCard label="Tabelas com alertas" value={number(q.filter(x=>x.status!=='ok').length)} foot="campos nulos/duplicados"/></div>
 <div className="grid grid-12"><Panel className="span-12" title="Pipeline RAW → Gold → motores" subtitle="Fluxo de referência; nem todas as etapas têm persistência nesta build" icon="▥"><div className="pipeline">{(data.pipeline||[]).map(x=><div key={x} className="pipe-step">{x}</div>)}</div></Panel><Panel className="span-12" title="Qualidade e linhagem da base" subtitle="Linha de origem acessível; duplicidades requerem chave de negócio para qualificar erro" icon="▣"><DataTable rows={q} onRowClick={r=>onDrill('','')} columns={columns([['sheet','Aba'],['rows','Registros',number],['columns','Colunas',number],['missing_cells','Células vazias',number],['duplicates','Linhas repetidas',number],['status','Status']])}/></Panel><Panel className="span-12" title="Upload, mapeamento e publicação" subtitle="Governança necessária antes de persistir no ambiente serverless" icon="!"><div className="notice">RAW, DE/PARA, histórico, qualidade e publicação durável: PENDENTE DE INFRAESTRUTURA. O servidor não grava nova base ativa. Esta demonstração usa somente o Excel versionado no backend; não existe confirmação enganosa de publicação.</div></Panel></div>
 </>
}
