export function fmtNumber(v,d=0){ if(v===null||v===undefined||Number.isNaN(Number(v))) return '—'; return Number(v).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d}) }
export function fmtPct(v,d=1){ if(v===null||v===undefined||Number.isNaN(Number(v))) return '—'; return `${(Number(v)*100).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d})}%` }
export function fmtMoney(v){ if(v===null||v===undefined||Number.isNaN(Number(v))) return '—'; const n=Number(v); if(Math.abs(n)>=1e6) return `R$ ${(n/1e6).toLocaleString('pt-BR',{maximumFractionDigits:2})} mi`; if(Math.abs(n)>=1e3) return `R$ ${(n/1e3).toLocaleString('pt-BR',{maximumFractionDigits:0})} mil`; return `R$ ${n.toLocaleString('pt-BR',{maximumFractionDigits:0})}` }

export function PageHeader({title,subtitle,plant,setPlant,plants=[],months=[],start,setStart,end,setEnd,extra}){
 const dates=months.length?months:[]
 return <header className="page-header"><div className="page-title-wrap"><h1>{title}</h1><p>{subtitle}</p></div><div className="page-controls">
 {plant!==undefined&&<label><span>Planta</span><select value={plant} onChange={e=>setPlant?.(e.target.value)}>{plants.map(p=><option key={p} value={p}>{p}</option>)}</select></label>}
 <label><span>Início</span><select aria-label="Início do período" value={start||''} onChange={e=>setStart?.(e.target.value)}><option value="">Primeira competência</option>{dates.map(m=><option key={m} value={m}>{m}</option>)}</select></label>
 <label><span>Fim</span><select aria-label="Fim do período" value={end||''} onChange={e=>setEnd?.(e.target.value)}><option value="">Última competência</option>{dates.map(m=><option key={m} value={m}>{m}</option>)}</select></label>
 {extra}</div></header>
}
export function IconBox({children='▦',tone='blue'}){ return <span className={`icon-box ${tone}`}>{children}</span> }
export function KpiCard({label,value,foot,state='info',icon='▦'}){ return <article className="kpi-card"><IconBox>{icon}</IconBox><div className="kpi-body"><span className="kpi-label">{label}</span><strong className="kpi-value">{value}</strong><span className={`kpi-foot ${state}`}>{foot}</span></div></article> }
export function Panel({title,subtitle,tag,icon='▦',children,className=''}){ return <section className={`panel ${className}`}><div className="panel-head"><div className="panel-head-left"><IconBox>{icon}</IconBox><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div></div>{tag&&<span className="tag">{tag}</span>}</div><div className="panel-body">{children}</div></section> }
export function Progress({value,state='good'}){ const w=Math.max(0,Math.min(100,(value||0)*100)); return <div className="progress"><i className={state} style={{width:`${w}%`}}/></div> }
export function StatusBadge({children,state='good'}){ return <span className={`status-badge ${state}`}>{children}</span> }
export function DataTable({columns,rows,onRowClick}){ return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows?.map((r,i)=><tr key={i} className={onRowClick?'drillable':''} role={onRowClick?'button':undefined} tabIndex={onRowClick?0:undefined} onClick={onRowClick?()=>onRowClick(r):undefined} onKeyDown={onRowClick?e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onRowClick(r)}}:undefined}>{columns.map(c=><td key={c.key}>{c.render?c.render(r[c.key],r):String(r[c.key]??'—')}</td>)}</tr>)}</tbody></table>{(!rows||rows.length===0)&&<p className="data-note">Sem linhas disponíveis para este filtro.</p>}</div> }
export function EmptyState({title='Em desenvolvimento',text='Este módulo está no radar da v1.0 e será implementado após o fechamento do núcleo principal.'}){ return <div className="empty-state"><IconBox>◇</IconBox><h2>{title}</h2><p>{text}</p></div> }
